{"3.4.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope3-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://cheeseshop.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://cheeseshop.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.4.0/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.4.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"833c54e0629d335f2ab595df749be90e96c8826d932158c784f922f5f02ff2cf","md5":"b4f24d4e040811dfa90ae4d96865a717","sha256":"de7dfd1d1a90ba58d1a3efcb1933f44a1190b701f960dc7f99c82c9cec2cb024"},"downloads":-1,"filename":"zope.app.exception-3.4.0.tar.gz","has_sig":false,"md5_digest":"b4f24d4e040811dfa90ae4d96865a717","packagetype":"sdist","python_version":"source","requires_python":null,"size":7891,"upload_time":"2007-10-24T13:49:11","upload_time_iso_8601":"2007-10-24T13:49:11Z","url":"https://files.pythonhosted.org/packages/83/3c/54e0629d335f2ab595df749be90e96c8826d932158c784f922f5f02ff2cf/zope.app.exception-3.4.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.4.0a1":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope3-dev@zope.org","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://svn.zope.org/zope.app.exception","keywords":null,"license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://svn.zope.org/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.4.0a1/","requires_dist":null,"requires_python":null,"summary":"UNKNOWN","version":"3.4.0a1","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"81853485752e0b2d52ef261f34321648f8171260d0f00635338abb7af8d16ea3","md5":"8684ad88af255cd752f7ddd1a8656be4","sha256":"b1e753c5bc7b94441e88cd680d08fcde7c53a80c4f3fe2c2ba2d32d3d13413ce"},"downloads":-1,"filename":"zope.app.exception-3.4.0a1.tar.gz","has_sig":false,"md5_digest":"8684ad88af255cd752f7ddd1a8656be4","packagetype":"sdist","python_version":"source","requires_python":null,"size":7469,"upload_time":"2007-04-23T13:30:57","upload_time_iso_8601":"2007-04-23T13:30:57Z","url":"https://files.pythonhosted.org/packages/81/85/3485752e0b2d52ef261f34321648f8171260d0f00635338abb7af8d16ea3/zope.app.exception-3.4.0a1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.4.1":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope3-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://cheeseshop.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://cheeseshop.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.4.1/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.4.1","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"9462b0dd485dd4fbf471f87b5615893d4bc6a1de5db7e54ad6ed69ac8da56a92","md5":"46c2758e8a9d305ff5869781b3171f26","sha256":"49fd3704e171bdb444330c1fc880355968fac2f2ab7d05ac437f6eecea334c60"},"downloads":-1,"filename":"zope.app.exception-3.4.1.tar.gz","has_sig":false,"md5_digest":"46c2758e8a9d305ff5869781b3171f26","packagetype":"sdist","python_version":"source","requires_python":null,"size":7953,"upload_time":"2007-10-31T18:46:49","upload_time_iso_8601":"2007-10-31T18:46:49Z","url":"https://files.pythonhosted.org/packages/94/62/b0dd485dd4fbf471f87b5615893d4bc6a1de5db7e54ad6ed69ac8da56a92/zope.app.exception-3.4.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.4.2":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.4.2/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.4.2","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"0ae13e184e81ae43d1bbf6cb3089216300c76eabe1639e57e9bcd22c10b5d318","md5":"727daa0b51cb8189ce208b33edc358e6","sha256":"7295f1e2a4cd2c09bb6e68c61c9739b101343fa170654cd8808c6582b46bf083"},"downloads":-1,"filename":"zope.app.exception-3.4.2.tar.gz","has_sig":false,"md5_digest":"727daa0b51cb8189ce208b33edc358e6","packagetype":"sdist","python_version":"source","requires_python":null,"size":8618,"upload_time":"2009-01-27T08:26:23","upload_time_iso_8601":"2009-01-27T08:26:23Z","url":"https://files.pythonhosted.org/packages/0a/e1/3e184e81ae43d1bbf6cb3089216300c76eabe1639e57e9bcd22c10b5d318/zope.app.exception-3.4.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.5.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.5.0/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.5.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"013a659b3f16d0129107008f3fb0016b17a249d9c4af7a3721e9444b12acb27a","md5":"2464f985b260fc72a71aff74eb70100f","sha256":"60d1ccc1fbf0635fe072f7e3544fe7d3e6d7706f2221d97582baca149565576e"},"downloads":-1,"filename":"zope.app.exception-3.5.0.tar.gz","has_sig":false,"md5_digest":"2464f985b260fc72a71aff74eb70100f","packagetype":"sdist","python_version":"source","requires_python":null,"size":9124,"upload_time":"2009-04-06T11:07:01","upload_time_iso_8601":"2009-04-06T11:07:01.298555Z","url":"https://files.pythonhosted.org/packages/01/3a/659b3f16d0129107008f3fb0016b17a249d9c4af7a3721e9444b12acb27a/zope.app.exception-3.5.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.6.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.6.0/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.6.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"6859ac76b602ef88b5cb01f6054bdd4cb310403219e9048e41b3184c2511e1b8","md5":"a56d7a5dcdd6fcc5b1e06ec71eca6f56","sha256":"640dc6c43904a917b342f699a18e9ec67e351b6d83ee5dad51eaac25fa2823f8"},"downloads":-1,"filename":"zope.app.exception-3.6.0.tar.gz","has_sig":false,"md5_digest":"a56d7a5dcdd6fcc5b1e06ec71eca6f56","packagetype":"sdist","python_version":"source","requires_python":null,"size":8330,"upload_time":"2010-01-09T11:40:57","upload_time_iso_8601":"2010-01-09T11:40:57.461659Z","url":"https://files.pythonhosted.org/packages/68/59/ac76b602ef88b5cb01f6054bdd4cb310403219e9048e41b3184c2511e1b8/zope.app.exception-3.6.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.6.1":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.6.1/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.6.1","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"079074dce6107fd14ef5df2cf18e33f92e4a1b827081a55281df3b01b235679d","md5":"19447ab2da8237011c0bf4302c9b8ba1","sha256":"6a05cd72958605f08238d8c33ee452a0482e2e0dc31e4a98f744c1534a430c2a"},"downloads":-1,"filename":"zope.app.exception-3.6.1.tar.gz","has_sig":false,"md5_digest":"19447ab2da8237011c0bf4302c9b8ba1","packagetype":"sdist","python_version":"source","requires_python":null,"size":10096,"upload_time":"2010-01-08T22:46:01","upload_time_iso_8601":"2010-01-08T22:46:01.945201Z","url":"https://files.pythonhosted.org/packages/07/90/74dce6107fd14ef5df2cf18e33f92e4a1b827081a55281df3b01b235679d/zope.app.exception-3.6.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.6.2":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.6.2/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.6.2","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"03668c9be4b61fb7425204285e575e372c5e8c5c0099f5d3894080419eea5976","md5":"55b0cdb634eb9c6a6615138f679dbd74","sha256":"522ffe2b8636c4be611477b8ac26bd105a259ad3090725ba4ee9d4444fb0c254"},"downloads":-1,"filename":"zope.app.exception-3.6.2.tar.gz","has_sig":false,"md5_digest":"55b0cdb634eb9c6a6615138f679dbd74","packagetype":"sdist","python_version":"source","requires_python":null,"size":7962,"upload_time":"2010-09-14T15:30:06","upload_time_iso_8601":"2010-09-14T15:30:06.512427Z","url":"https://files.pythonhosted.org/packages/03/66/8c9be4b61fb7425204285e575e372c5e8c5c0099f5d3894080419eea5976/zope.app.exception-3.6.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"3.6.3":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":null,"maintainer_email":null,"name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/3.6.3/","requires_dist":null,"requires_python":null,"summary":"Zope 3 exception views","version":"3.6.3","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"4d9130cf40e8ba9a25600af8c2a896c61a7f3febbda6025abfc69babb769d6ed","md5":"af161d3e7c17db7f56f7816a6f2d980c","sha256":"4689647ce1ff1104ea9e451ee4c0a7bd0be0c0bbbcb6a16039f8052f13feeb63"},"downloads":-1,"filename":"zope.app.exception-3.6.3.tar.gz","has_sig":false,"md5_digest":"af161d3e7c17db7f56f7816a6f2d980c","packagetype":"sdist","python_version":"source","requires_python":null,"size":8738,"upload_time":"2011-05-23T15:31:57","upload_time_iso_8601":"2011-05-23T15:31:57.648934Z","url":"https://files.pythonhosted.org/packages/4d/91/30cf40e8ba9a25600af8c2a896c61a7f3febbda6025abfc69babb769d6ed/zope.app.exception-3.6.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"4.0.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Programming Language :: Python :: 2","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3","Programming Language :: Python :: 3.3","Programming Language :: Python :: 3.4","Programming Language :: Python :: 3.5","Programming Language :: Python :: 3.6","Programming Language :: Python :: Implementation :: CPython","Programming Language :: Python :: Implementation :: PyPy","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":"","maintainer_email":"","name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/4.0.0/","requires_dist":["zope.authentication","setuptools","zope.browser (>=1.2)","zope.browserpage (>=3.11.0)","zope.component","zope.interface","zope.publisher (>=3.12)","zope.security","webtest; extra == 'test'","zope.app.appsetup; extra == 'test'","zope.app.basicskin (>=4.0); extra == 'test'","zope.app.pagetemplate; extra == 'test'","zope.app.publication; extra == 'test'","zope.app.wsgi; extra == 'test'","zope.browsermenu; extra == 'test'","zope.browserresource; extra == 'test'","zope.container; extra == 'test'","zope.login; extra == 'test'","zope.password; extra == 'test'","zope.principalregistry; extra == 'test'","zope.publisher; extra == 'test'","zope.securitypolicy; extra == 'test'","zope.site; extra == 'test'","zope.testrunner; extra == 'test'"],"requires_python":"","summary":"Zope 3 exception views","version":"4.0.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"0eb7f375f239c987239eff0b4b517bf6a7c820b8e43d0c82e0692730d7c1b102","md5":"da719cc5320453977dcfe205bcb11961","sha256":"a8fd9639373fdd2745aa140b3874c69636f2609e6f2f35e68f1f41905f528948"},"downloads":-1,"filename":"zope.app.exception-4.0.0-py2.py3-none-any.whl","has_sig":false,"md5_digest":"da719cc5320453977dcfe205bcb11961","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":17817,"upload_time":"2017-05-01T18:34:43","upload_time_iso_8601":"2017-05-01T18:34:43.287120Z","url":"https://files.pythonhosted.org/packages/0e/b7/f375f239c987239eff0b4b517bf6a7c820b8e43d0c82e0692730d7c1b102/zope.app.exception-4.0.0-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"0c60c59b3da45cf8b9cc625a7db7e8e6ccc059a2984b9b8561ae1821c1e6638a","md5":"86c3efec97bc1fea0e2085685119e2bc","sha256":"2e7d8ddba8e569c577571029338be184dac8509cce24e8472a1541d85a8efe79"},"downloads":-1,"filename":"zope.app.exception-4.0.0.tar.gz","has_sig":false,"md5_digest":"86c3efec97bc1fea0e2085685119e2bc","packagetype":"sdist","python_version":"source","requires_python":null,"size":13112,"upload_time":"2017-05-01T18:34:44","upload_time_iso_8601":"2017-05-01T18:34:44.902110Z","url":"https://files.pythonhosted.org/packages/0c/60/c59b3da45cf8b9cc625a7db7e8e6ccc059a2984b9b8561ae1821c1e6638a/zope.app.exception-4.0.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"4.0.1":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Programming Language :: Python :: 2","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3","Programming Language :: Python :: 3.3","Programming Language :: Python :: 3.4","Programming Language :: Python :: 3.5","Programming Language :: Python :: 3.6","Programming Language :: Python :: Implementation :: CPython","Programming Language :: Python :: Implementation :: PyPy","Topic :: Internet :: WWW/HTTP"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":"","maintainer_email":"","name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"UNKNOWN","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/4.0.1/","requires_dist":["setuptools","zope.authentication","zope.browser (>=1.2)","zope.browserpage (>=3.11.0)","zope.component","zope.interface","zope.publisher (>=3.12)","zope.security","webtest; extra == 'test'","zope.app.appsetup; extra == 'test'","zope.app.basicskin (>=4.0); extra == 'test'","zope.app.pagetemplate; extra == 'test'","zope.app.publication; extra == 'test'","zope.app.wsgi; extra == 'test'","zope.browsermenu; extra == 'test'","zope.browserresource; extra == 'test'","zope.container; extra == 'test'","zope.login; extra == 'test'","zope.password; extra == 'test'","zope.principalregistry; extra == 'test'","zope.publisher; extra == 'test'","zope.securitypolicy; extra == 'test'","zope.site; extra == 'test'","zope.testrunner; extra == 'test'"],"requires_python":"","summary":"Zope 3 exception views","version":"4.0.1","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"ba8586c3137f2a513cd8327b333567214e0cb5cbd1d840fc2d6acb0fb73565af","md5":"b4a64a7513e3fce86d20bc3f4bfc843f","sha256":"eaa85cec2e298b921f4647a23f0b541cc78c707cf3f5799fc97cb137cb89771c"},"downloads":-1,"filename":"zope.app.exception-4.0.1-py2.py3-none-any.whl","has_sig":false,"md5_digest":"b4a64a7513e3fce86d20bc3f4bfc843f","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":18251,"upload_time":"2017-05-15T14:59:53","upload_time_iso_8601":"2017-05-15T14:59:53.680192Z","url":"https://files.pythonhosted.org/packages/ba/85/86c3137f2a513cd8327b333567214e0cb5cbd1d840fc2d6acb0fb73565af/zope.app.exception-4.0.1-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"1415bf30e445fde70d08f55ac66c2a9b73a75950c22c08692733580787f05111","md5":"37703e9dd6f3b357bf7dc0c5b6d76760","sha256":"6addded3f918792fd6d90946cca687e3dc7c149a558f6652f7d78cc26e8999d4"},"downloads":-1,"filename":"zope.app.exception-4.0.1.tar.gz","has_sig":false,"md5_digest":"37703e9dd6f3b357bf7dc0c5b6d76760","packagetype":"sdist","python_version":"source","requires_python":null,"size":13483,"upload_time":"2017-05-15T14:59:55","upload_time_iso_8601":"2017-05-15T14:59:55.704158Z","url":"https://files.pythonhosted.org/packages/14/15/bf30e445fde70d08f55ac66c2a9b73a75950c22c08692733580787f05111/zope.app.exception-4.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"4.1.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope :: 3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Programming Language :: Python :: 2","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3","Programming Language :: Python :: 3.5","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Programming Language :: Python :: Implementation :: CPython","Programming Language :: Python :: Implementation :: PyPy","Topic :: Internet :: WWW/HTTP"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":"","maintainer_email":"","name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":"","project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/4.1.0/","requires_dist":["setuptools","zope.interface","zope.publisher (>=3.12)","zope.authentication","zope.browser (>=1.2)","zope.browserpage (>=3.11.0)","zope.component","zope.security","webtest ; extra == 'test'","zope.app.appsetup ; extra == 'test'","zope.app.basicskin (>=4.0) ; extra == 'test'","zope.app.pagetemplate ; extra == 'test'","zope.app.publication ; extra == 'test'","zope.app.wsgi ; extra == 'test'","zope.browsermenu ; extra == 'test'","zope.browserresource ; extra == 'test'","zope.container ; extra == 'test'","zope.login ; extra == 'test'","zope.password ; extra == 'test'","zope.principalregistry ; extra == 'test'","zope.publisher ; extra == 'test'","zope.securitypolicy ; extra == 'test'","zope.site ; extra == 'test'","zope.testrunner ; extra == 'test'"],"requires_python":"","summary":"Zope 3 exception views","version":"4.1.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"056436c095e3b5225957c48a11d25aff43718927c79b37002e6af2252f56ebad","md5":"7e61a3ae84b13b466719f734fe052854","sha256":"2aaee86e7804373b782981ff526a3ba6d628eac4d9fec015be6c515a8ac15411"},"downloads":-1,"filename":"zope.app.exception-4.1.0-py2.py3-none-any.whl","has_sig":false,"md5_digest":"7e61a3ae84b13b466719f734fe052854","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":17089,"upload_time":"2021-03-22T07:49:12","upload_time_iso_8601":"2021-03-22T07:49:12.254722Z","url":"https://files.pythonhosted.org/packages/05/64/36c095e3b5225957c48a11d25aff43718927c79b37002e6af2252f56ebad/zope.app.exception-4.1.0-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"667983b8a4c34ed06a9aa943f176a6c7caf0ad29a8eb2652d88e36361f130891","md5":"6bc3ee5b7ca32d1fd19a97f818be2eb5","sha256":"ad84a087c16ea583e4ddc31ea0ee7097425fb6432b3813f02500611f2a683eab"},"downloads":-1,"filename":"zope.app.exception-4.1.0.tar.gz","has_sig":false,"md5_digest":"6bc3ee5b7ca32d1fd19a97f818be2eb5","packagetype":"sdist","python_version":"source","requires_python":null,"size":11485,"upload_time":"2021-03-22T07:49:14","upload_time_iso_8601":"2021-03-22T07:49:14.114866Z","url":"https://files.pythonhosted.org/packages/66/79/83b8a4c34ed06a9aa943f176a6c7caf0ad29a8eb2652d88e36361f130891/zope.app.exception-4.1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"5.0":{"info":{"author":"Zope Corporation and Contributors","author_email":"zope-dev@zope.dev","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Environment :: Web Environment","Framework :: Zope :: 3","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Programming Language :: Python :: Implementation :: CPython","Programming Language :: Python :: Implementation :: PyPy","Topic :: Internet :: WWW/HTTP"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/zope.app.exception","keywords":"zope3 exception view","license":"ZPL 2.1","maintainer":"","maintainer_email":"","name":"zope.app.exception","package_url":"https://pypi.org/project/zope.app.exception/","platform":null,"project_url":"https://pypi.org/project/zope.app.exception/","project_urls":{"Homepage":"http://pypi.python.org/pypi/zope.app.exception"},"provides_extra":null,"release_url":"https://pypi.org/project/zope.app.exception/5.0/","requires_dist":["setuptools","zope.interface","zope.publisher (>=3.12)","zope.authentication","zope.browser (>=1.2)","zope.browserpage (>=3.11.0)","zope.component","zope.security","webtest ; extra == 'test'","zope.app.appsetup ; extra == 'test'","zope.app.basicskin (>=4.0) ; extra == 'test'","zope.app.pagetemplate ; extra == 'test'","zope.app.publication ; extra == 'test'","zope.app.wsgi ; extra == 'test'","zope.browsermenu ; extra == 'test'","zope.browserresource ; extra == 'test'","zope.container ; extra == 'test'","zope.login ; extra == 'test'","zope.password ; extra == 'test'","zope.principalregistry ; extra == 'test'","zope.publisher ; extra == 'test'","zope.securitypolicy ; extra == 'test'","zope.site ; extra == 'test'","zope.testrunner ; extra == 'test'"],"requires_python":">=3.7","summary":"Zope 3 exception views","version":"5.0","yanked":false,"yanked_reason":null},"last_serial":23498793,"urls":[{"comment_text":"","digests":{"blake2b_256":"cde3bde64805f216c53a0f62f23e5992c76f64202bf949eed8811efeb4d40b73","md5":"16b0f9c497fa80ea8ee12640a8639a73","sha256":"3bca4b21817f51cc1e525f2658cb6ad55c1d96c095937923f94132b70cb28936"},"downloads":-1,"filename":"zope.app.exception-5.0-py3-none-any.whl","has_sig":false,"md5_digest":"16b0f9c497fa80ea8ee12640a8639a73","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":17035,"upload_time":"2023-02-07T09:35:57","upload_time_iso_8601":"2023-02-07T09:35:57.409834Z","url":"https://files.pythonhosted.org/packages/cd/e3/bde64805f216c53a0f62f23e5992c76f64202bf949eed8811efeb4d40b73/zope.app.exception-5.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"51c3a2c92f73bd16491d8ce2a41867e70a7520dc08e3dcbe284570c176d80e33","md5":"5ab868d0408384dc6b6a4f4ad10d6bbd","sha256":"3d65d6cdd008aa21bc891fe663a8440d566b1a8def1713e1a87ad3f4b9ade5bd"},"downloads":-1,"filename":"zope.app.exception-5.0.tar.gz","has_sig":false,"md5_digest":"5ab868d0408384dc6b6a4f4ad10d6bbd","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":13346,"upload_time":"2023-02-07T09:35:59","upload_time_iso_8601":"2023-02-07T09:35:59.402949Z","url":"https://files.pythonhosted.org/packages/51/c3/a2c92f73bd16491d8ce2a41867e70a7520dc08e3dcbe284570c176d80e33/zope.app.exception-5.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}