{"1.0.10":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.12","Programming Language :: Python :: 3.9","Topic :: Software Development :: Libraries :: Python Modules"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"decorator, exception handling, exponential backoff, python, retry","license":"MIT","maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":{"changelog":"https://github.com/sylvainmouquet/reattempt/releases","documentation":"https://github.com/sylvainmouquet/reattempt","homepage":"https://github.com/sylvainmouquet/reattempt","repository":"https://github.com/sylvainmouquet/reattempt"},"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.0.10/","requires_dist":null,"requires_python":">=3.9","summary":"Retrying a python function when exceptions are raised","version":"1.0.10","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"e18430d92f5d4f6a1c76c9c67fa97f5a8da1e6c23dd20c72b6da8d10bb8ac173","md5":"bd3b2b3be2a2a45425c91a4f3f45c759","sha256":"54962f6db26f9a5929d25e8fbcea522517ef4c36017e03b968abe0957d29258b"},"downloads":-1,"filename":"reattempt-1.0.10-py3-none-any.whl","has_sig":false,"md5_digest":"bd3b2b3be2a2a45425c91a4f3f45c759","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9","size":4518,"upload_time":"2024-09-24T15:42:30","upload_time_iso_8601":"2024-09-24T15:42:30.491804Z","url":"https://files.pythonhosted.org/packages/e1/84/30d92f5d4f6a1c76c9c67fa97f5a8da1e6c23dd20c72b6da8d10bb8ac173/reattempt-1.0.10-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"439266078a6d4018d803f85db2a7232cf3469f1e0bc58cb8ea962a17818363b0","md5":"4402399baf55c08ca624c2c289fd673f","sha256":"56046a7ce9b345f32454371d5459eeb4a81efafbda8cbed3be243a6bd3d9e2c9"},"downloads":-1,"filename":"reattempt-1.0.10.tar.gz","has_sig":false,"md5_digest":"4402399baf55c08ca624c2c289fd673f","packagetype":"sdist","python_version":"source","requires_python":">=3.9","size":12044,"upload_time":"2024-09-24T15:42:32","upload_time_iso_8601":"2024-09-24T15:42:32.802092Z","url":"https://files.pythonhosted.org/packages/43/92/66078a6d4018d803f85db2a7232cf3469f1e0bc58cb8ea962a17818363b0/reattempt-1.0.10.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.9":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":[],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.0.9/","requires_dist":null,"requires_python":">=3.9","summary":"Retrying a python function when exceptions are raised","version":"1.0.9","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"f104badf28449198223e834b628d5a431477560f8d6dc6670ff650912eb4b487","md5":"9630c66ca2f439b87d9da4c94a4eac05","sha256":"56d498f6adedd5169ca295f16a96ceeb18c7e8c290b1566b57b2f115ad379126"},"downloads":-1,"filename":"reattempt-1.0.9-py3-none-any.whl","has_sig":false,"md5_digest":"9630c66ca2f439b87d9da4c94a4eac05","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9","size":4268,"upload_time":"2024-09-24T15:32:49","upload_time_iso_8601":"2024-09-24T15:32:49.837711Z","url":"https://files.pythonhosted.org/packages/f1/04/badf28449198223e834b628d5a431477560f8d6dc6670ff650912eb4b487/reattempt-1.0.9-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"97df8c091ae38fb895f117496d749259837186ac59e790e2072d99617b87dfd5","md5":"8337071835c26af65f821c0a4b80b9e5","sha256":"93b6043e9926cb132f4f16800d05ad1c85fe17a7fbe19da919a5d9a6e39a2a04"},"downloads":-1,"filename":"reattempt-1.0.9.tar.gz","has_sig":false,"md5_digest":"8337071835c26af65f821c0a4b80b9e5","packagetype":"sdist","python_version":"source","requires_python":">=3.9","size":11719,"upload_time":"2024-09-24T15:32:51","upload_time_iso_8601":"2024-09-24T15:32:51.074080Z","url":"https://files.pythonhosted.org/packages/97/df/8c091ae38fb895f117496d749259837186ac59e790e2072d99617b87dfd5/reattempt-1.0.9.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.0":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.12","Programming Language :: Python :: 3.9","Topic :: Software Development :: Libraries :: Python Modules"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"async, async gen, decorator, exception handling, exponential backoff, generator, python, retry, sync","license":"MIT","maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":{"changelog":"https://github.com/sylvainmouquet/reattempt/releases","documentation":"https://github.com/sylvainmouquet/reattempt","homepage":"https://github.com/sylvainmouquet/reattempt","repository":"https://github.com/sylvainmouquet/reattempt"},"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.1.0/","requires_dist":null,"requires_python":">=3.9","summary":"Retrying a python function when exceptions are raised","version":"1.1.0","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"55a555dcbee6826e1921b09fee8b96712fc00024a3e2959dd06c8c82798ef4e8","md5":"d256ec8720196aa74d8b4d6da37f8a92","sha256":"9b9630a23c739d1d0526204f364eab3c437e333ba530245a6e4cf698fbb60eac"},"downloads":-1,"filename":"reattempt-1.1.0-py3-none-any.whl","has_sig":false,"md5_digest":"d256ec8720196aa74d8b4d6da37f8a92","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9","size":5165,"upload_time":"2024-09-27T10:30:41","upload_time_iso_8601":"2024-09-27T10:30:41.638236Z","url":"https://files.pythonhosted.org/packages/55/a5/55dcbee6826e1921b09fee8b96712fc00024a3e2959dd06c8c82798ef4e8/reattempt-1.1.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"27220592e908fce3574db5c82f5a54fcec6e8c8f69b94134fe75b2651b86c199","md5":"3c90ad91c8565747479b69b47a6eabe9","sha256":"ea7ec030b3bdb0bf12e23e7a555498525560d9d09b303a0f7df33e12f6a57a21"},"downloads":-1,"filename":"reattempt-1.1.0.tar.gz","has_sig":false,"md5_digest":"3c90ad91c8565747479b69b47a6eabe9","packagetype":"sdist","python_version":"source","requires_python":">=3.9","size":43350,"upload_time":"2024-09-27T10:30:43","upload_time_iso_8601":"2024-09-27T10:30:43.176411Z","url":"https://files.pythonhosted.org/packages/27/22/0592e908fce3574db5c82f5a54fcec6e8c8f69b94134fe75b2651b86c199/reattempt-1.1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.1":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.12","Programming Language :: Python :: 3.9","Topic :: Software Development :: Libraries :: Python Modules"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"async, async gen, decorator, exception handling, exponential backoff, generator, python, retry, sync","license":"MIT","maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":{"changelog":"https://github.com/sylvainmouquet/reattempt/releases","documentation":"https://github.com/sylvainmouquet/reattempt","homepage":"https://github.com/sylvainmouquet/reattempt","repository":"https://github.com/sylvainmouquet/reattempt"},"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.1.1/","requires_dist":null,"requires_python":">=3.9","summary":"Retrying a python function when exceptions are raised","version":"1.1.1","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"8d5193b12a90183ebca00098203c861e6a26f89e7f31b0048b1c554891be9a7f","md5":"043cf2b76c90a819fb5512a636774b7b","sha256":"d5f14b4f1d14485339062296224cf1fe2ee28523c9a50d9166a5fa39acf77f8c"},"downloads":-1,"filename":"reattempt-1.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"043cf2b76c90a819fb5512a636774b7b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9","size":5161,"upload_time":"2024-10-02T08:04:42","upload_time_iso_8601":"2024-10-02T08:04:42.387055Z","url":"https://files.pythonhosted.org/packages/8d/51/93b12a90183ebca00098203c861e6a26f89e7f31b0048b1c554891be9a7f/reattempt-1.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"62809b4cfa3ee9fd02759b421b6b33aa9c8d02d31a252d33a9ed082cb7374ee3","md5":"3f6af492a544d40bfaf77ed2fe030a82","sha256":"7c1b819f3110cd41564743b5dc15a6e14327c0242c65390c40a6f84e58ed1e92"},"downloads":-1,"filename":"reattempt-1.1.1.tar.gz","has_sig":false,"md5_digest":"3f6af492a544d40bfaf77ed2fe030a82","packagetype":"sdist","python_version":"source","requires_python":">=3.9","size":43541,"upload_time":"2024-10-02T08:04:43","upload_time_iso_8601":"2024-10-02T08:04:43.589746Z","url":"https://files.pythonhosted.org/packages/62/80/9b4cfa3ee9fd02759b421b6b33aa9c8d02d31a252d33a9ed082cb7374ee3/reattempt-1.1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.2":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.12","Programming Language :: Python :: 3.13","Topic :: Software Development :: Libraries :: Python Modules"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"async, async gen, decorator, exception handling, exponential backoff, generator, python, retry, sync","license":"MIT","maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":{"changelog":"https://github.com/sylvainmouquet/reattempt/releases","documentation":"https://github.com/sylvainmouquet/reattempt","homepage":"https://github.com/sylvainmouquet/reattempt","repository":"https://github.com/sylvainmouquet/reattempt"},"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.1.2/","requires_dist":null,"requires_python":">=3.9","summary":"Retrying a python function when exceptions are raised","version":"1.1.2","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"e7a933afc6273d883a97ab361f6bcb17cd661092ee84e27e2e9560e7b97efcbf","md5":"52dc5725fe161717436f86342df8d423","sha256":"3d58075814f149da73e8cca8403d118758d4c7ab5d2d85a988274f02d281e565"},"downloads":-1,"filename":"reattempt-1.1.2-py3-none-any.whl","has_sig":false,"md5_digest":"52dc5725fe161717436f86342df8d423","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9","size":5164,"upload_time":"2024-10-09T18:46:33","upload_time_iso_8601":"2024-10-09T18:46:33.681349Z","url":"https://files.pythonhosted.org/packages/e7/a9/33afc6273d883a97ab361f6bcb17cd661092ee84e27e2e9560e7b97efcbf/reattempt-1.1.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"e22324a9e584da82c428716335503f2f60d37aa829434a7371312ff8da065f92","md5":"eea930df7f431ff57966d2174b907800","sha256":"293ba4f4de7b078d79731567da155fda844260b7ac4866fde3584fb7e525ea65"},"downloads":-1,"filename":"reattempt-1.1.2.tar.gz","has_sig":false,"md5_digest":"eea930df7f431ff57966d2174b907800","packagetype":"sdist","python_version":"source","requires_python":">=3.9","size":50801,"upload_time":"2024-10-09T18:46:35","upload_time_iso_8601":"2024-10-09T18:46:35.005773Z","url":"https://files.pythonhosted.org/packages/e2/23/24a9e584da82c428716335503f2f60d37aa829434a7371312ff8da065f92/reattempt-1.1.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.3":{"info":{"author":null,"author_email":"Sylvain Mouquet <sylvain.mouquet@gmail.com>","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Programming Language :: Python","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.12","Programming Language :: Python :: 3.13","Topic :: Software Development :: Libraries :: Python Modules"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"async, async gen, decorator, exception handling, exponential backoff, generator, python, retry, sync","license":"MIT","maintainer":null,"maintainer_email":null,"name":"reattempt","package_url":"https://pypi.org/project/reattempt/","platform":null,"project_url":"https://pypi.org/project/reattempt/","project_urls":{"changelog":"https://github.com/sylvainmouquet/reattempt/releases","documentation":"https://github.com/sylvainmouquet/reattempt","homepage":"https://github.com/sylvainmouquet/reattempt","repository":"https://github.com/sylvainmouquet/reattempt"},"provides_extra":null,"release_url":"https://pypi.org/project/reattempt/1.1.3/","requires_dist":null,"requires_python":">=3.10","summary":"Retrying a python function when exceptions are raised","version":"1.1.3","yanked":false,"yanked_reason":null},"last_serial":25400854,"urls":[{"comment_text":"","digests":{"blake2b_256":"9518c9839bc6ed1a88dcfc58d0e9e119ddc3864289eeafa2ad01cc0384239e7c","md5":"7043a530d578a04ac3d8745a9092c2a6","sha256":"8c9193c7f6c4d186dc1475321c890e64306bfa6348bae91922baf1ba37b9241f"},"downloads":-1,"filename":"reattempt-1.1.3-py3-none-any.whl","has_sig":false,"md5_digest":"7043a530d578a04ac3d8745a9092c2a6","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":5162,"upload_time":"2024-10-09T18:58:36","upload_time_iso_8601":"2024-10-09T18:58:36.254653Z","url":"https://files.pythonhosted.org/packages/95/18/c9839bc6ed1a88dcfc58d0e9e119ddc3864289eeafa2ad01cc0384239e7c/reattempt-1.1.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"358da56393bbb21da5a63c359c516d6f065660984e49b6fda755a04e37d56c08","md5":"0b5f2292fd20717ace40f9121f08fe7a","sha256":"de04b069bfb3e5bf09ccfec0163d93bc6ae0595badca43b7eb36483057996ff1"},"downloads":-1,"filename":"reattempt-1.1.3.tar.gz","has_sig":false,"md5_digest":"0b5f2292fd20717ace40f9121f08fe7a","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":44613,"upload_time":"2024-10-09T18:58:37","upload_time_iso_8601":"2024-10-09T18:58:37.885411Z","url":"https://files.pythonhosted.org/packages/35/8d/a56393bbb21da5a63c359c516d6f065660984e49b6fda755a04e37d56c08/reattempt-1.1.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}