{"0.1.0":{"info":{"author":"parkminwoo","author_email":"parkminwoo1991@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 2 - Pre-Alpha","Intended Audience :: Science/Research","License :: OSI Approved :: MIT License","Natural Language :: English","Programming Language :: Python","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Programming Language :: Python :: Implementation :: CPython","Topic :: Scientific/Engineering :: Artificial Intelligence"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/dsdanielpark/CatchException","keywords":"Exception,Python,Python Exception Alarm,Error notifications,Customizable notifications,Traceback management,Single line alarm","license":"","maintainer":"","maintainer_email":"","name":"catchexception","package_url":"https://pypi.org/project/catchexception/","platform":null,"project_url":"https://pypi.org/project/catchexception/","project_urls":{"Homepage":"https://github.com/dsdanielpark/CatchException"},"provides_extra":null,"release_url":"https://pypi.org/project/catchexception/0.1.0/","requires_dist":null,"requires_python":">=3.6","summary":"With Python's try-except statement, experience a significantly more flexible way to receive notifications.","version":"0.1.0","yanked":false,"yanked_reason":null},"last_serial":18184362,"urls":[{"comment_text":"","digests":{"blake2b_256":"cbbd89ffe6394dbefcaad68a3e39ace68ad0b73127109fa413079dbfce3c1f42","md5":"2afb1972624c7337fb9ccb7859ed821e","sha256":"d19963a9960b34c935029a4cd90aa2e50adb99f80dac39986459f98295bd98c9"},"downloads":-1,"filename":"catchexception-0.1.0-py3-none-any.whl","has_sig":false,"md5_digest":"2afb1972624c7337fb9ccb7859ed821e","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":6143,"upload_time":"2023-04-13T16:40:23","upload_time_iso_8601":"2023-04-13T16:40:23.244983Z","url":"https://files.pythonhosted.org/packages/cb/bd/89ffe6394dbefcaad68a3e39ace68ad0b73127109fa413079dbfce3c1f42/catchexception-0.1.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"c6a5da3d66a96b4c34b96c64d15b069cfb866819b2a52005e0013880a726da0f","md5":"1b46781ead900f3ed986e1cc622cd010","sha256":"b4908895647585e5dd25d9ed3ea0c5508f2341ed04f5350349265a2ca239abb8"},"downloads":-1,"filename":"catchexception-0.1.0.tar.gz","has_sig":false,"md5_digest":"1b46781ead900f3ed986e1cc622cd010","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":5323,"upload_time":"2023-04-13T16:40:26","upload_time_iso_8601":"2023-04-13T16:40:26.132986Z","url":"https://files.pythonhosted.org/packages/c6/a5/da3d66a96b4c34b96c64d15b069cfb866819b2a52005e0013880a726da0f/catchexception-0.1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.1":{"info":{"author":"daniel park","author_email":"parkminwoo1991@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 3 - Alpha","Intended Audience :: Science/Research","License :: OSI Approved :: MIT License","Natural Language :: English","Programming Language :: Python","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Topic :: Scientific/Engineering :: Artificial Intelligence"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/dsdanielpark/ExceptNotifier","keywords":"Exception,Python,Python Exception Alarm,Error notifications,Customizable notifications,Traceback management,Single line alarm","license":"","maintainer":"","maintainer_email":"","name":"catchexception","package_url":"https://pypi.org/project/catchexception/","platform":null,"project_url":"https://pypi.org/project/catchexception/","project_urls":{"Homepage":"https://github.com/dsdanielpark/ExceptNotifier"},"provides_extra":null,"release_url":"https://pypi.org/project/catchexception/0.1.1/","requires_dist":["twilio","plyer","openai","discord","sphinx-rtd-theme","Sphinx","bardapi"],"requires_python":">=3.6","summary":"With Python's try-except to receive notifications about Errors or Successes in your code through messenger app or email.","version":"0.1.1","yanked":false,"yanked_reason":null},"last_serial":18184362,"urls":[{"comment_text":"","digests":{"blake2b_256":"382cabc336df197b5dd51e813cc259946c5b301929fcc310a39812ab5934f326","md5":"dee4d8b7dab863ec1b3bf4bde8f5881e","sha256":"ff25d06a2451e566e23df1c5282d69c965d61cded0a2234ae08f76e1a7ef9c4f"},"downloads":-1,"filename":"catchexception-0.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"dee4d8b7dab863ec1b3bf4bde8f5881e","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":61036,"upload_time":"2023-05-15T19:13:02","upload_time_iso_8601":"2023-05-15T19:13:02.737506Z","url":"https://files.pythonhosted.org/packages/38/2c/abc336df197b5dd51e813cc259946c5b301929fcc310a39812ab5934f326/catchexception-0.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"802fe2e90e8f0e55b2938b19f96b9d8bb801121b5b49b4e20cd59f1400c8f970","md5":"d0ceb8511ffc2330418de801f70c43b7","sha256":"78b8be73e763312947e4d3e0e24a43045f34d34a5baf5638c35dcd46cf3404ec"},"downloads":-1,"filename":"catchexception-0.1.1.tar.gz","has_sig":false,"md5_digest":"d0ceb8511ffc2330418de801f70c43b7","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":20159,"upload_time":"2023-05-15T19:13:19","upload_time_iso_8601":"2023-05-15T19:13:19.801873Z","url":"https://files.pythonhosted.org/packages/80/2f/e2e90e8f0e55b2938b19f96b9d8bb801121b5b49b4e20cd59f1400c8f970/catchexception-0.1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.2":{"info":{"author":"daniel park","author_email":"parkminwoo1991@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 3 - Alpha","Intended Audience :: Science/Research","License :: OSI Approved :: MIT License","Natural Language :: English","Programming Language :: Python","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Topic :: Scientific/Engineering :: Artificial Intelligence"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/dsdanielpark/ExceptNotifier","keywords":"Exception,Python,Python Exception Alarm,Error notifications,Customizable notifications,Traceback management,Single line alarm","license":"","maintainer":"","maintainer_email":"","name":"catchexception","package_url":"https://pypi.org/project/catchexception/","platform":null,"project_url":"https://pypi.org/project/catchexception/","project_urls":{"Homepage":"https://github.com/dsdanielpark/ExceptNotifier"},"provides_extra":null,"release_url":"https://pypi.org/project/catchexception/0.1.2/","requires_dist":["twilio","plyer","openai","discord","sphinx-rtd-theme","Sphinx","bardapi","urllib3","requests"],"requires_python":">=3.6","summary":"With Python's try-except to receive notifications about Errors or Successes in your code through messenger app or email.","version":"0.1.2","yanked":false,"yanked_reason":null},"last_serial":18184362,"urls":[{"comment_text":"","digests":{"blake2b_256":"d4cb7d025deacd32ab0b09139786cbbc8c5c687f603363c6cb4545298f5fbe38","md5":"1ced1f89576866dcd52d7ee06cb36331","sha256":"f73282e5a8439c8e1249bc6e2fa35b92fd04b464439c0645d66b616cd2cad954"},"downloads":-1,"filename":"catchexception-0.1.2-py3-none-any.whl","has_sig":false,"md5_digest":"1ced1f89576866dcd52d7ee06cb36331","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":2600,"upload_time":"2023-05-20T21:27:15","upload_time_iso_8601":"2023-05-20T21:27:15.632192Z","url":"https://files.pythonhosted.org/packages/d4/cb/7d025deacd32ab0b09139786cbbc8c5c687f603363c6cb4545298f5fbe38/catchexception-0.1.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"f4ec36c4830588b6db2c15e696dafd90b4ec9ea9b15452aeb964c2e87edd3396","md5":"b12cdcb62fb352e4159b5d802c9af089","sha256":"f5b45b4e54bf8f239a632770da9e3e9f4dbc793aeadf101439958b541d006aec"},"downloads":-1,"filename":"catchexception-0.1.2.tar.gz","has_sig":false,"md5_digest":"b12cdcb62fb352e4159b5d802c9af089","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":2596,"upload_time":"2023-05-20T21:27:19","upload_time_iso_8601":"2023-05-20T21:27:19.392932Z","url":"https://files.pythonhosted.org/packages/f4/ec/36c4830588b6db2c15e696dafd90b4ec9ea9b15452aeb964c2e87edd3396/catchexception-0.1.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}