{"1.0":{"info":{"author":"Plone Security Team","author_email":"security@plone.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Framework :: Plone","Framework :: Plone :: 4.0","Framework :: Plone :: 4.1","Framework :: Plone :: 4.2","Framework :: Plone :: 4.3","Framework :: Plone :: 5.0","Framework :: Plone :: 5.1","Framework :: Plone :: 5.2","License :: OSI Approved :: GNU General Public License (GPL)","Programming Language :: Python","Programming Language :: Python :: 2.6","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://plone.org/security/hotfix/20200121","keywords":"plone security hotfix patch","license":"GPL","maintainer":"","maintainer_email":"","name":"Products.PloneHotfix20200121","package_url":"https://pypi.org/project/Products.PloneHotfix20200121/","platform":"","project_url":"https://pypi.org/project/Products.PloneHotfix20200121/","project_urls":{"Homepage":"https://plone.org/security/hotfix/20200121"},"provides_extra":null,"release_url":"https://pypi.org/project/Products.PloneHotfix20200121/1.0/","requires_dist":["setuptools"],"requires_python":"","summary":"Various Plone hotfixes, 2020-01-21","version":"1.0","yanked":false,"yanked_reason":null},"last_serial":18472996,"urls":[{"comment_text":"","digests":{"blake2b_256":"664221664a56f5fe50ddc33add9eb681483a1d901a5d08832ec16b6ca33c608b","md5":"06cbb2ba08e844f73a40fb55e7cff1dc","sha256":"a10f485984fb28a704cc13ef147dafb0f46c56eef2e56a03f9222b39edfb0b89"},"downloads":-1,"filename":"Products.PloneHotfix20200121-1.0-py2.py3-none-any.whl","has_sig":false,"md5_digest":"06cbb2ba08e844f73a40fb55e7cff1dc","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":27674,"upload_time":"2020-01-21T15:00:05","upload_time_iso_8601":"2020-01-21T15:00:05.259305Z","url":"https://files.pythonhosted.org/packages/66/42/21664a56f5fe50ddc33add9eb681483a1d901a5d08832ec16b6ca33c608b/Products.PloneHotfix20200121-1.0-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"bcc681f5428a13bd5cc92003d5a7a1057fb24e90d7358f8b38c205f7dbe5f74a","md5":"c9c643e4f71e50356433d4baa408d319","sha256":"b82c103c36ddcfe1528aee4e501e1230d055e6d604155e8b612b075ad8c4edab"},"downloads":-1,"filename":"Products.PloneHotfix20200121-1.0.tar.gz","has_sig":false,"md5_digest":"c9c643e4f71e50356433d4baa408d319","packagetype":"sdist","python_version":"source","requires_python":null,"size":17203,"upload_time":"2020-01-21T15:00:06","upload_time_iso_8601":"2020-01-21T15:00:06.733004Z","url":"https://files.pythonhosted.org/packages/bc/c6/81f5428a13bd5cc92003d5a7a1057fb24e90d7358f8b38c205f7dbe5f74a/Products.PloneHotfix20200121-1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1":{"info":{"author":"Plone Security Team","author_email":"security@plone.org","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Framework :: Plone","Framework :: Plone :: 4.0","Framework :: Plone :: 4.1","Framework :: Plone :: 4.2","Framework :: Plone :: 4.3","Framework :: Plone :: 5.0","Framework :: Plone :: 5.1","Framework :: Plone :: 5.2","License :: OSI Approved :: GNU General Public License (GPL)","Programming Language :: Python","Programming Language :: Python :: 2.6","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://plone.org/security/hotfix/20200121","keywords":"plone security hotfix patch","license":"GPL","maintainer":"","maintainer_email":"","name":"Products.PloneHotfix20200121","package_url":"https://pypi.org/project/Products.PloneHotfix20200121/","platform":"","project_url":"https://pypi.org/project/Products.PloneHotfix20200121/","project_urls":{"Homepage":"https://plone.org/security/hotfix/20200121"},"provides_extra":null,"release_url":"https://pypi.org/project/Products.PloneHotfix20200121/1.1/","requires_dist":["setuptools"],"requires_python":"","summary":"Various Plone hotfixes, 2020-01-21","version":"1.1","yanked":false,"yanked_reason":null},"last_serial":18472996,"urls":[{"comment_text":"","digests":{"blake2b_256":"ee2b40106603d4d22fa3189bdcfe396c93ddccfb225be5e851f4db4bc49ebc7b","md5":"289652d191367cdb098e2c773cb7340e","sha256":"78fcd2132df95ba290d2469d552a7c4421ff5c6b66fad59e19e3bc1b5f179c6a"},"downloads":-1,"filename":"Products.PloneHotfix20200121-1.1-py2.py3-none-any.whl","has_sig":false,"md5_digest":"289652d191367cdb098e2c773cb7340e","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":28529,"upload_time":"2020-02-11T22:47:25","upload_time_iso_8601":"2020-02-11T22:47:25.440539Z","url":"https://files.pythonhosted.org/packages/ee/2b/40106603d4d22fa3189bdcfe396c93ddccfb225be5e851f4db4bc49ebc7b/Products.PloneHotfix20200121-1.1-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"b3f74054119d5a9cd92d274e5d86ee81761792ae7a3e0a5e1a0a01e78e139c3e","md5":"f819eaaf60643a794be73d96d9c9bb72","sha256":"9f4c55f75aa9a2e15d778a514cf38d7134fe248eabc364f75680941194f5b1df"},"downloads":-1,"filename":"Products.PloneHotfix20200121-1.1.tar.gz","has_sig":false,"md5_digest":"f819eaaf60643a794be73d96d9c9bb72","packagetype":"sdist","python_version":"source","requires_python":null,"size":17950,"upload_time":"2020-02-11T22:47:27","upload_time_iso_8601":"2020-02-11T22:47:27.157541Z","url":"https://files.pythonhosted.org/packages/b3/f7/4054119d5a9cd92d274e5d86ee81761792ae7a3e0a5e1a0a01e78e139c3e/Products.PloneHotfix20200121-1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}