{"0.1.1":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.1/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.1","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"7e4cb397a070c4c108d774ff3fb99b3f42375f7e76e110e4e11c88dae8592232","md5":"aacee8bdfc3cfa8ba75799fe99413ae1","sha256":"f2389a2a86fccaca197480812521b0b39ba6ed78c3cd6ad5d1f2c524f2de1e99"},"downloads":-1,"filename":"django_dbconn_retry-0.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"aacee8bdfc3cfa8ba75799fe99413ae1","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":7117,"upload_time":"2018-01-21T15:09:24","upload_time_iso_8601":"2018-01-21T15:09:24.154914Z","url":"https://files.pythonhosted.org/packages/7e/4c/b397a070c4c108d774ff3fb99b3f42375f7e76e110e4e11c88dae8592232/django_dbconn_retry-0.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.2":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.2/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.2","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"ba8aece6b780f5b53064ffcb56ef8de116aaab6458b9d5f7916b729d94bcca93","md5":"bab98aff900b92df8e75844c011a9d11","sha256":"35388e1b29d5dcd3bde7ba8cc577e1972b4a9f55cc2879b28e102e8b0f7f12da"},"downloads":-1,"filename":"django_dbconn_retry-0.1.2-py3-none-any.whl","has_sig":false,"md5_digest":"bab98aff900b92df8e75844c011a9d11","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":8127,"upload_time":"2018-01-22T00:36:43","upload_time_iso_8601":"2018-01-22T00:36:43.319324Z","url":"https://files.pythonhosted.org/packages/ba/8a/ece6b780f5b53064ffcb56ef8de116aaab6458b9d5f7916b729d94bcca93/django_dbconn_retry-0.1.2-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.3":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.3/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.3","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"5762427c104e023bf9c4583ef3a59fbc6a9cc081701e39ee8070fb602657ef6b","md5":"838bfa18141d7c30b04695c803648754","sha256":"9d16c628dc0dfdefbbac8785874e5e5cc16d471370dd478a828df47b9f0b0066"},"downloads":-1,"filename":"django_dbconn_retry-0.1.3-py3-none-any.whl","has_sig":false,"md5_digest":"838bfa18141d7c30b04695c803648754","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":8356,"upload_time":"2018-01-25T16:11:11","upload_time_iso_8601":"2018-01-25T16:11:11.657786Z","url":"https://files.pythonhosted.org/packages/57/62/427c104e023bf9c4583ef3a59fbc6a9cc081701e39ee8070fb602657ef6b/django_dbconn_retry-0.1.3-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.4":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.4/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.4","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"28b6cbcb2bb5dcbe2df8a95c1fb9b6bda5f1b047fc0eaabb3b76c39e7635fc95","md5":"5ae263fd0e1254d016e746914791a8da","sha256":"57e2a0c6667515212c6ec3a2f2688d15b7f9485e53b6ef3a01d756f52a2a63a0"},"downloads":-1,"filename":"django_dbconn_retry-0.1.4-py3-none-any.whl","has_sig":false,"md5_digest":"5ae263fd0e1254d016e746914791a8da","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":8479,"upload_time":"2018-01-28T23:24:44","upload_time_iso_8601":"2018-01-28T23:24:44.468165Z","url":"https://files.pythonhosted.org/packages/28/b6/cbcb2bb5dcbe2df8a95c1fb9b6bda5f1b047fc0eaabb3b76c39e7635fc95/django_dbconn_retry-0.1.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.5":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.5/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.5","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"4bc09ec20244371734f6b4596cc37b6675b21395b0ada4dca18e68210b222fd5","md5":"dfdcb8cdca541bc130eb26f4b76e0f74","sha256":"b0d9b8dad1ec8408213fbe99ec19b927363f4668f832ce89c3886830dd894d93"},"downloads":-1,"filename":"django_dbconn_retry-0.1.5-py3-none-any.whl","has_sig":false,"md5_digest":"dfdcb8cdca541bc130eb26f4b76e0f74","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":8630,"upload_time":"2018-01-29T10:27:26","upload_time_iso_8601":"2018-01-29T10:27:26.990722Z","url":"https://files.pythonhosted.org/packages/4b/c0/9ec20244371734f6b4596cc37b6675b21395b0ada4dca18e68210b222fd5/django_dbconn_retry-0.1.5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.6":{"info":{"author":"Jonas Maurus (@jdelic)","author_email":"jonas-dbconn-retry@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"GoPythonGo.com","maintainer_email":"info@gopythongo.com","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.6/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.6","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"903bcbd0ccb7e8d8395911713c34f1474cff854268a86275bc84bfe2fe7f94ee","md5":"30defce1cf6749fa6542174ebe4f1325","sha256":"220ba069ec05358b81b47b956a07eaa745dd2a46316985bfa831cb1e5b274af0"},"downloads":-1,"filename":"django_dbconn_retry-0.1.6-py3-none-any.whl","has_sig":false,"md5_digest":"30defce1cf6749fa6542174ebe4f1325","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":6735,"upload_time":"2022-01-04T12:38:20","upload_time_iso_8601":"2022-01-04T12:38:20.465060Z","url":"https://files.pythonhosted.org/packages/90/3b/cbd0ccb7e8d8395911713c34f1474cff854268a86275bc84bfe2fe7f94ee/django_dbconn_retry-0.1.6-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.7":{"info":{"author":"Jonas Maurus (@jdelic)","author_email":"jonas-dbconn-retry@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"GoPythonGo.com","maintainer_email":"info@gopythongo.com","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":null,"project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.7/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.7","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"9a25ac9d4c6e3c42feabd5148c5d323fc12c67cb180c59aab380018026d0f163","md5":"8674284fea6ff17bccd894815463c0cd","sha256":"eb7e85eb6c2de3157fe2a0bb8badfdfd440038c5f00cc60f8599b5825d5e98ed"},"downloads":-1,"filename":"django_dbconn_retry-0.1.7-py3-none-any.whl","has_sig":false,"md5_digest":"8674284fea6ff17bccd894815463c0cd","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":7052,"upload_time":"2022-08-21T22:07:13","upload_time_iso_8601":"2022-08-21T22:07:13.621940Z","url":"https://files.pythonhosted.org/packages/9a/25/ac9d4c6e3c42feabd5148c5d323fc12c67cb180c59aab380018026d0f163/django_dbconn_retry-0.1.7-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.8":{"info":{"author":"Jonas Maurus (@jdelic)","author_email":"jonas-dbconn-retry@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":null,"license":null,"maintainer":"GoPythonGo.com","maintainer_email":"info@gopythongo.com","name":"django-dbconn-retry","package_url":"https://pypi.org/project/django-dbconn-retry/","platform":null,"project_url":"https://pypi.org/project/django-dbconn-retry/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry/0.1.8/","requires_dist":null,"requires_python":null,"summary":"Patch Django to retry a database connection first before failing.","version":"0.1.8","yanked":false,"yanked_reason":null},"last_serial":25058253,"urls":[{"comment_text":"","digests":{"blake2b_256":"996458c8ae7f25514514c09a91b3542ef28e37b265905768c383949500301e8d","md5":"46a90b0d155b53df52e42fe6f4a9acdc","sha256":"be0fcb4d04d23655b431a6a6d9db80fd9f068d269e298caa4a284b6a45cf8ac4"},"downloads":-1,"filename":"django_dbconn_retry-0.1.8-py3-none-any.whl","has_sig":false,"md5_digest":"46a90b0d155b53df52e42fe6f4a9acdc","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":7094,"upload_time":"2024-09-16T21:36:03","upload_time_iso_8601":"2024-09-16T21:36:03.163189Z","url":"https://files.pythonhosted.org/packages/99/64/58c8ae7f25514514c09a91b3542ef28e37b265905768c383949500301e8d/django_dbconn_retry-0.1.8-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}