{"0.0.1":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.1/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"68938637903f30ff4d2ca4b327bbdf81013021eef713a6ad17df0553820400e5","md5":"1d6f874990874acc5a79b781763fb82b","sha256":"a91f0905942b3bc514b927f72f6f8580b93a61aa138cb72b6f11af70e791d54b"},"downloads":-1,"filename":"fastapi_exception-0.0.1-py3-none-any.whl","has_sig":false,"md5_digest":"1d6f874990874acc5a79b781763fb82b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":9568,"upload_time":"2023-09-10T07:28:58","upload_time_iso_8601":"2023-09-10T07:28:58.588104Z","url":"https://files.pythonhosted.org/packages/68/93/8637903f30ff4d2ca4b327bbdf81013021eef713a6ad17df0553820400e5/fastapi_exception-0.0.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"3d85b33f3fcf1afac7396c3e3dd877c4e57729ade66d71d4b2f84bec2845e8ea","md5":"525fbec27f8021375c89483ab6f4adf0","sha256":"5b767e11580465137ddd8222069a1af9895de6542c9d1b1fb323632bd2689d01"},"downloads":-1,"filename":"fastapi_exception-0.0.1.tar.gz","has_sig":false,"md5_digest":"525fbec27f8021375c89483ab6f4adf0","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5867,"upload_time":"2023-09-10T07:29:00","upload_time_iso_8601":"2023-09-10T07:29:00.697680Z","url":"https://files.pythonhosted.org/packages/3d/85/b33f3fcf1afac7396c3e3dd877c4e57729ade66d71d4b2f84bec2845e8ea/fastapi_exception-0.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.10":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.10/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.10","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"b0dfc0747f454b91646d4889cd2cebc140b6a664b4a78c332c6ee22a365d912b","md5":"8885db60439056ac69891821deca28c2","sha256":"2e153de652d91c61c809497a279a3fdc09289e1abb072b122c1a5f6f53e05b86"},"downloads":-1,"filename":"fastapi_exception-0.0.10-py3-none-any.whl","has_sig":false,"md5_digest":"8885db60439056ac69891821deca28c2","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10831,"upload_time":"2023-09-10T14:42:15","upload_time_iso_8601":"2023-09-10T14:42:15.339164Z","url":"https://files.pythonhosted.org/packages/b0/df/c0747f454b91646d4889cd2cebc140b6a664b4a78c332c6ee22a365d912b/fastapi_exception-0.0.10-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"098448425cc6401dac0afa57c0d19468bac2425ba0e17e2691ae2e0869e57332","md5":"0cea8e0624732188f87e9ea324ae74e7","sha256":"d8465ac64f30f01e09caba250569b0150982861fa91e2b2cc18175ecacb6a4f9"},"downloads":-1,"filename":"fastapi_exception-0.0.10.tar.gz","has_sig":false,"md5_digest":"0cea8e0624732188f87e9ea324ae74e7","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6634,"upload_time":"2023-09-10T14:42:17","upload_time_iso_8601":"2023-09-10T14:42:17.436355Z","url":"https://files.pythonhosted.org/packages/09/84/48425cc6401dac0afa57c0d19468bac2425ba0e17e2691ae2e0869e57332/fastapi_exception-0.0.10.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.11":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.11/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.11","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"75c77542d3d1258cd126aaf60e8d11ddef279be47dc15ba8c6d80b915d6a4bc2","md5":"8a1897d55ce0e356afb1f4ab70458534","sha256":"3d489943c3effc106984abb266e32acf3870aca805e805aa31fa7434c696ce2b"},"downloads":-1,"filename":"fastapi_exception-0.0.11-py3-none-any.whl","has_sig":false,"md5_digest":"8a1897d55ce0e356afb1f4ab70458534","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10428,"upload_time":"2023-09-10T14:58:35","upload_time_iso_8601":"2023-09-10T14:58:35.415492Z","url":"https://files.pythonhosted.org/packages/75/c7/7542d3d1258cd126aaf60e8d11ddef279be47dc15ba8c6d80b915d6a4bc2/fastapi_exception-0.0.11-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"c598b98f37ffc89e4a624769a932f58a97254233d45f6d89168037618a0a3a7e","md5":"f5d607b7c45901c84215ab0a1fcd0e4e","sha256":"9c6672f9b9deabdf88afcecd0db2d922dec2fc0569ad941726f0840d69facb54"},"downloads":-1,"filename":"fastapi_exception-0.0.11.tar.gz","has_sig":false,"md5_digest":"f5d607b7c45901c84215ab0a1fcd0e4e","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6650,"upload_time":"2023-09-10T14:58:37","upload_time_iso_8601":"2023-09-10T14:58:37.328850Z","url":"https://files.pythonhosted.org/packages/c5/98/b98f37ffc89e4a624769a932f58a97254233d45f6d89168037618a0a3a7e/fastapi_exception-0.0.11.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.12":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.12/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.12","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"b42dd54431fcf91e305497904c88cc2cd8b6872b58692153bdb0d08faa5fd56a","md5":"59219543f5c9f63e50b406de94c5c7de","sha256":"d78aaa79b7ad2570b04aed9a23b822f7f46c001316b29f8d311e44944483f364"},"downloads":-1,"filename":"fastapi_exception-0.0.12-py3-none-any.whl","has_sig":false,"md5_digest":"59219543f5c9f63e50b406de94c5c7de","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10438,"upload_time":"2023-09-10T15:10:14","upload_time_iso_8601":"2023-09-10T15:10:14.819621Z","url":"https://files.pythonhosted.org/packages/b4/2d/d54431fcf91e305497904c88cc2cd8b6872b58692153bdb0d08faa5fd56a/fastapi_exception-0.0.12-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"52d0f35e887a4347d9c912ec78f584e07eed4cf7b0ebfd745f4eec9a47dfe686","md5":"6107fc0392f4254d77905b69d01066c8","sha256":"e3beec55198be05e3708b62922b2e0114d9d43b6d56bf4c9fdc289cb173148cc"},"downloads":-1,"filename":"fastapi_exception-0.0.12.tar.gz","has_sig":false,"md5_digest":"6107fc0392f4254d77905b69d01066c8","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6655,"upload_time":"2023-09-10T15:10:17","upload_time_iso_8601":"2023-09-10T15:10:17.056101Z","url":"https://files.pythonhosted.org/packages/52/d0/f35e887a4347d9c912ec78f584e07eed4cf7b0ebfd745f4eec9a47dfe686/fastapi_exception-0.0.12.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.14":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.14/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.14","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"5d6f3e51fbf67590a50943a8b008e788786c2ffa83f3b63fe9b59d1b67937e24","md5":"92c3d38782014e1ddf2fedefa14f1149","sha256":"1ca9d315ef91ee95ed2f665cc41036d66ba1d4a6c01eed925c8e4e8ecacb6e1c"},"downloads":-1,"filename":"fastapi_exception-0.0.14-py3-none-any.whl","has_sig":false,"md5_digest":"92c3d38782014e1ddf2fedefa14f1149","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10420,"upload_time":"2023-09-11T02:48:58","upload_time_iso_8601":"2023-09-11T02:48:58.886358Z","url":"https://files.pythonhosted.org/packages/5d/6f/3e51fbf67590a50943a8b008e788786c2ffa83f3b63fe9b59d1b67937e24/fastapi_exception-0.0.14-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"3dc0dfd4819f9400a2b6504f14a35d1b3fa5bff227c6091eb65872096a77d282","md5":"0980ca6c5f3024baaa5b099147b85a3c","sha256":"82f1849b1a416a7feed6ea33609d03203db9c73a50b19d234043d97e94edf87f"},"downloads":-1,"filename":"fastapi_exception-0.0.14.tar.gz","has_sig":false,"md5_digest":"0980ca6c5f3024baaa5b099147b85a3c","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6664,"upload_time":"2023-09-11T02:49:01","upload_time_iso_8601":"2023-09-11T02:49:01.001131Z","url":"https://files.pythonhosted.org/packages/3d/c0/dfd4819f9400a2b6504f14a35d1b3fa5bff227c6091eb65872096a77d282/fastapi_exception-0.0.14.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.15":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.15/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.15","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"f68681638f5a69f4232687e432f06f66e1604e16c95e801d6445b6fd270307f5","md5":"c74ac70e9f76b8d691bd7761fbdd2755","sha256":"20041530b0e1a692caea36b17917448aec57d912f7c528385e44b3902a945c37"},"downloads":-1,"filename":"fastapi_exception-0.0.15-py3-none-any.whl","has_sig":false,"md5_digest":"c74ac70e9f76b8d691bd7761fbdd2755","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10788,"upload_time":"2023-09-11T07:51:18","upload_time_iso_8601":"2023-09-11T07:51:18.975279Z","url":"https://files.pythonhosted.org/packages/f6/86/81638f5a69f4232687e432f06f66e1604e16c95e801d6445b6fd270307f5/fastapi_exception-0.0.15-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"c58f46632907ee42e0e310e2340e69e883dba3602a99bf17cf8a5a0cab158e1f","md5":"25c3cf3093c25cd82faff9a29dc97ed0","sha256":"49d265d6e1cc24f929bfbba34482e23265cd8c7650df2b8727ea976c34486874"},"downloads":-1,"filename":"fastapi_exception-0.0.15.tar.gz","has_sig":false,"md5_digest":"25c3cf3093c25cd82faff9a29dc97ed0","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6754,"upload_time":"2023-09-11T07:51:21","upload_time_iso_8601":"2023-09-11T07:51:21.298628Z","url":"https://files.pythonhosted.org/packages/c5/8f/46632907ee42e0e310e2340e69e883dba3602a99bf17cf8a5a0cab158e1f/fastapi_exception-0.0.15.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.16":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.16/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.16","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"d508429aacc1b9e51752522927c49297d59a277a7ca8585dfa1d32194f561ea5","md5":"feda6c4b5f8bf323b618312aed99f973","sha256":"c52b91c7077a42afa803983be0581f416a5f8696665cc036c72edfbc54c8dd05"},"downloads":-1,"filename":"fastapi_exception-0.0.16-py3-none-any.whl","has_sig":false,"md5_digest":"feda6c4b5f8bf323b618312aed99f973","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10833,"upload_time":"2023-09-11T07:56:36","upload_time_iso_8601":"2023-09-11T07:56:36.522237Z","url":"https://files.pythonhosted.org/packages/d5/08/429aacc1b9e51752522927c49297d59a277a7ca8585dfa1d32194f561ea5/fastapi_exception-0.0.16-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"57f57b3f1f50f822b7cd9cad189ae9b2b5567b2a7d9842048aca2ddf9440ed37","md5":"b441b980df2ed6422bf949140f9a8935","sha256":"f6df1bf7836db89974f581a9fd5e8e6539b01b3c3ad4586acd34850bcf21a059"},"downloads":-1,"filename":"fastapi_exception-0.0.16.tar.gz","has_sig":false,"md5_digest":"b441b980df2ed6422bf949140f9a8935","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6775,"upload_time":"2023-09-11T07:56:38","upload_time_iso_8601":"2023-09-11T07:56:38.402644Z","url":"https://files.pythonhosted.org/packages/57/f5/7b3f1f50f822b7cd9cad189ae9b2b5567b2a7d9842048aca2ddf9440ed37/fastapi_exception-0.0.16.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.2":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.2/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.2","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"e9579dd6807fd117f730985e79ecc7e1082e78917756d3efec88208334484246","md5":"175a138ea3362424496614bfded02fd0","sha256":"15b1b0c4f50652127bb2ed81a0e16745432ba4d9cc3239d0e5e3b238d90c708d"},"downloads":-1,"filename":"fastapi_exception-0.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"175a138ea3362424496614bfded02fd0","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":9662,"upload_time":"2023-09-10T08:08:45","upload_time_iso_8601":"2023-09-10T08:08:45.049870Z","url":"https://files.pythonhosted.org/packages/e9/57/9dd6807fd117f730985e79ecc7e1082e78917756d3efec88208334484246/fastapi_exception-0.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"866e1a4a75133179e3d22e75f435e6a9b1f669deaaab45195e05a2eb2483f347","md5":"184e99b7070d9b5018865d707f743124","sha256":"fc30db0701b4add2b8fca4aca1e1e4102b517fa79357a2c7f5bac68e154ee474"},"downloads":-1,"filename":"fastapi_exception-0.0.2.tar.gz","has_sig":false,"md5_digest":"184e99b7070d9b5018865d707f743124","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5931,"upload_time":"2023-09-10T08:08:46","upload_time_iso_8601":"2023-09-10T08:08:46.523949Z","url":"https://files.pythonhosted.org/packages/86/6e/1a4a75133179e3d22e75f435e6a9b1f669deaaab45195e05a2eb2483f347/fastapi_exception-0.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.3":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.3/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"9082892a3880eb57ad98c70a9b1b796fdd3806f8e72042548802dae9e004c048","md5":"ee6e65c04afa351843fe3bea96eb2d00","sha256":"d706ff049d096d0397eca4a14c392e4a7a0e8e800e9978d746660764d06a6f12"},"downloads":-1,"filename":"fastapi_exception-0.0.3-py3-none-any.whl","has_sig":false,"md5_digest":"ee6e65c04afa351843fe3bea96eb2d00","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":9662,"upload_time":"2023-09-10T08:11:25","upload_time_iso_8601":"2023-09-10T08:11:25.801273Z","url":"https://files.pythonhosted.org/packages/90/82/892a3880eb57ad98c70a9b1b796fdd3806f8e72042548802dae9e004c048/fastapi_exception-0.0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"0f8ecc69471a986e050e6e3252fb6b086dc75e497807ef82c6d7d40d534a012e","md5":"573836f273db98ba5954366170d40dee","sha256":"96a5070db6dd3453b8b7f48ae40790bc92b709d6a79c89a5092d45b64e42d9d6"},"downloads":-1,"filename":"fastapi_exception-0.0.3.tar.gz","has_sig":false,"md5_digest":"573836f273db98ba5954366170d40dee","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5930,"upload_time":"2023-09-10T08:11:27","upload_time_iso_8601":"2023-09-10T08:11:27.888665Z","url":"https://files.pythonhosted.org/packages/0f/8e/cc69471a986e050e6e3252fb6b086dc75e497807ef82c6d7d40d534a012e/fastapi_exception-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.4":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.4/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.4","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"84c5e855c1939ec3f6286a9ce7f87f605b13d18eaf5a555289c39280c16d80c0","md5":"2fdd623b809b9b43c986166eb994e6ba","sha256":"d4650d78cb5b16a4fc030ca9bea53aace225c2e166fbfe389c58bc597a65db31"},"downloads":-1,"filename":"fastapi_exception-0.0.4-py3-none-any.whl","has_sig":false,"md5_digest":"2fdd623b809b9b43c986166eb994e6ba","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10140,"upload_time":"2023-09-10T08:32:02","upload_time_iso_8601":"2023-09-10T08:32:02.078072Z","url":"https://files.pythonhosted.org/packages/84/c5/e855c1939ec3f6286a9ce7f87f605b13d18eaf5a555289c39280c16d80c0/fastapi_exception-0.0.4-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"8f2b557c29e5b3c0f514dbfa2cb7d1ed5015ad775e16e5cab2f20567bdf2ba68","md5":"4b960711dd140bd6e2dec5908727a63d","sha256":"a65d34cccaf7e26a255c8d4d796bfe06cfb8507ad611d6ca1f5ca2cff789a755"},"downloads":-1,"filename":"fastapi_exception-0.0.4.tar.gz","has_sig":false,"md5_digest":"4b960711dd140bd6e2dec5908727a63d","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5978,"upload_time":"2023-09-10T08:32:04","upload_time_iso_8601":"2023-09-10T08:32:04.140321Z","url":"https://files.pythonhosted.org/packages/8f/2b/557c29e5b3c0f514dbfa2cb7d1ed5015ad775e16e5cab2f20567bdf2ba68/fastapi_exception-0.0.4.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.5":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.5/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.5","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"719af7305888a4572d030944f5771b0a1a07fddd906d1b4ee7a8cd760cc19fd4","md5":"69a5b64b5bec9125fc70d6c68ceb977b","sha256":"3e495e1d276320ad03673934dfab479b21a26d666f52c8724e5f42c46c773802"},"downloads":-1,"filename":"fastapi_exception-0.0.5-py3-none-any.whl","has_sig":false,"md5_digest":"69a5b64b5bec9125fc70d6c68ceb977b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10072,"upload_time":"2023-09-10T08:35:03","upload_time_iso_8601":"2023-09-10T08:35:03.736773Z","url":"https://files.pythonhosted.org/packages/71/9a/f7305888a4572d030944f5771b0a1a07fddd906d1b4ee7a8cd760cc19fd4/fastapi_exception-0.0.5-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"3280782a6fa8419c6e6cc270214fc13a1d6e5375da52e677b3285ad4def91cbc","md5":"9cb62ffe5fb4eedd762b07f5cdab2ccf","sha256":"a467c2a5beee8c7b6e6b82ebc3c6345a7909956ff9a032bb5db1c9883845a381"},"downloads":-1,"filename":"fastapi_exception-0.0.5.tar.gz","has_sig":false,"md5_digest":"9cb62ffe5fb4eedd762b07f5cdab2ccf","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5925,"upload_time":"2023-09-10T08:35:05","upload_time_iso_8601":"2023-09-10T08:35:05.678625Z","url":"https://files.pythonhosted.org/packages/32/80/782a6fa8419c6e6cc270214fc13a1d6e5375da52e677b3285ad4def91cbc/fastapi_exception-0.0.5.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.6":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.6/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.6","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"803687f4be0de3109940203b0fc3b675edde373d18ad590c5a3c19c48777e8fd","md5":"4b2e640927f3857f1a9d5d71858a2021","sha256":"5429f7cc48bfb6e4d1d10cc6a2f655bb1a54a02800892e0f6f6c3efbbb70696e"},"downloads":-1,"filename":"fastapi_exception-0.0.6-py3-none-any.whl","has_sig":false,"md5_digest":"4b2e640927f3857f1a9d5d71858a2021","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10060,"upload_time":"2023-09-10T09:14:57","upload_time_iso_8601":"2023-09-10T09:14:57.319170Z","url":"https://files.pythonhosted.org/packages/80/36/87f4be0de3109940203b0fc3b675edde373d18ad590c5a3c19c48777e8fd/fastapi_exception-0.0.6-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"813038386ed3005408dfde561d64256afc7816789d64a8bd721a276d05cec75d","md5":"133050ccb598f1df0f793b87b4d7b694","sha256":"5a2e38fd6476397cb0b8d0e45c79860edd530bf913d0a4201a6d0622c1e251b0"},"downloads":-1,"filename":"fastapi_exception-0.0.6.tar.gz","has_sig":false,"md5_digest":"133050ccb598f1df0f793b87b4d7b694","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5913,"upload_time":"2023-09-10T09:14:59","upload_time_iso_8601":"2023-09-10T09:14:59.351379Z","url":"https://files.pythonhosted.org/packages/81/30/38386ed3005408dfde561d64256afc7816789d64a8bd721a276d05cec75d/fastapi_exception-0.0.6.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.7":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.7/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.7","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"ef16e256f27008b57d92bb311361ed6600c6221856042d7c7058d11edfeb95c0","md5":"1de6187ac9eb43b7837b4363652a333b","sha256":"cb622f1c7d7c4b7d579de9db664522e79df576740e3f57449eb6f874c6b6ca1c"},"downloads":-1,"filename":"fastapi_exception-0.0.7-py3-none-any.whl","has_sig":false,"md5_digest":"1de6187ac9eb43b7837b4363652a333b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10060,"upload_time":"2023-09-10T09:17:13","upload_time_iso_8601":"2023-09-10T09:17:13.964193Z","url":"https://files.pythonhosted.org/packages/ef/16/e256f27008b57d92bb311361ed6600c6221856042d7c7058d11edfeb95c0/fastapi_exception-0.0.7-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"11d1b6edea9cff8795ace8534642d2193fb4bb3fe9f24fb8fbfcbff4e298b0e2","md5":"7e929ba9860f5fb88f420ed8f4b9ec51","sha256":"bb07b8375136ec490772a75e0eb0de3d635cb25cc6d627ab460cba2e44ab09ae"},"downloads":-1,"filename":"fastapi_exception-0.0.7.tar.gz","has_sig":false,"md5_digest":"7e929ba9860f5fb88f420ed8f4b9ec51","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":5914,"upload_time":"2023-09-10T09:17:15","upload_time_iso_8601":"2023-09-10T09:17:15.565481Z","url":"https://files.pythonhosted.org/packages/11/d1/b6edea9cff8795ace8534642d2193fb4bb3fe9f24fb8fbfcbff4e298b0e2/fastapi_exception-0.0.7.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.8":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.8/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.8","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"f19c806b18d484849bf4cb6cac5cd0ff3d9f23e8b89ffb39cac96ec8728a4b45","md5":"9b7fd929ed8cac13eda3b1b521c7451e","sha256":"e750f6a24530abf5249199c48b63d4bdeb72ea668f6e7153fec900acf7a2ffb0"},"downloads":-1,"filename":"fastapi_exception-0.0.8-py3-none-any.whl","has_sig":false,"md5_digest":"9b7fd929ed8cac13eda3b1b521c7451e","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10640,"upload_time":"2023-09-10T09:23:49","upload_time_iso_8601":"2023-09-10T09:23:49.302481Z","url":"https://files.pythonhosted.org/packages/f1/9c/806b18d484849bf4cb6cac5cd0ff3d9f23e8b89ffb39cac96ec8728a4b45/fastapi_exception-0.0.8-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"da4e8c62793cc0aa79d73d9ba0df3ca521241317c2598ab73abd5c034ecba3e4","md5":"b6103cd97f410fd3827338c06bfe1378","sha256":"8e72f2076f1d7cc33cc33ae44fc61a871b568047c4f31e8907d527bcc4f479c9"},"downloads":-1,"filename":"fastapi_exception-0.0.8.tar.gz","has_sig":false,"md5_digest":"b6103cd97f410fd3827338c06bfe1378","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6161,"upload_time":"2023-09-10T09:23:51","upload_time_iso_8601":"2023-09-10T09:23:51.181080Z","url":"https://files.pythonhosted.org/packages/da/4e/8c62793cc0aa79d73d9ba0df3ca521241317c2598ab73abd5c034ecba3e4/fastapi_exception-0.0.8.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.9":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-event/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/0.0.9/","requires_dist":null,"requires_python":">=3.10","summary":"FastAPI Event","version":"0.0.9","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"7f5a0f247b684b14559cb18cc53a675f5c070f55cd4846d9fa923e5f0264a1fd","md5":"a5eb0a091763900a5e7f03a816d73bc5","sha256":"6ed7a733cde555b6c211d5b7539771225140e88d1af037ec2fbced4981b25bb5"},"downloads":-1,"filename":"fastapi_exception-0.0.9-py3-none-any.whl","has_sig":false,"md5_digest":"a5eb0a091763900a5e7f03a816d73bc5","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":10832,"upload_time":"2023-09-10T09:33:12","upload_time_iso_8601":"2023-09-10T09:33:12.696161Z","url":"https://files.pythonhosted.org/packages/7f/5a/0f247b684b14559cb18cc53a675f5c070f55cd4846d9fa923e5f0264a1fd/fastapi_exception-0.0.9-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"5fcd84ac8611c80eb6a75cdac48fa964f4aad46ef847b31dc7598ddd7f56840f","md5":"bed7965343c1233b81e0d443e44371ed","sha256":"2a46b54cd990a9c73f3cd1d6c069ed1f50cdee9bd5d3aa58febd3ed4ff93ffe7"},"downloads":-1,"filename":"fastapi_exception-0.0.9.tar.gz","has_sig":false,"md5_digest":"bed7965343c1233b81e0d443e44371ed","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":6274,"upload_time":"2023-09-10T09:33:14","upload_time_iso_8601":"2023-09-10T09:33:14.627559Z","url":"https://files.pythonhosted.org/packages/5f/cd/84ac8611c80eb6a75cdac48fa964f4aad46ef847b31dc7598ddd7f56840f/fastapi_exception-0.0.9.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.0":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.0.0/","requires_dist":["pydantic==2.4.2"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.0.0","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"52da01ce64cea1ec354cd114bd010d5b86a90c515a10aea530fe9b1ab8db2985","md5":"e5a9ee9bd8ad066e8bb5d11ea6fc289d","sha256":"bb6af882f10731c76539b9c20b5b31117831b2fc5fb7c1dde191e4fb644e0167"},"downloads":-1,"filename":"fastapi_exception-1.0.0-py3-none-any.whl","has_sig":false,"md5_digest":"e5a9ee9bd8ad066e8bb5d11ea6fc289d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":11327,"upload_time":"2023-09-28T20:04:02","upload_time_iso_8601":"2023-09-28T20:04:02.375125Z","url":"https://files.pythonhosted.org/packages/52/da/01ce64cea1ec354cd114bd010d5b86a90c515a10aea530fe9b1ab8db2985/fastapi_exception-1.0.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"de49955e4c6c91477978f9d4eb88f88dece5cff3509a3302440dafb90eae7df0","md5":"aa3ae99d7643cfd30fa06f7fc63af088","sha256":"64d3caf713962a762f7ae66b2f0003b03ef0edb911551139a0a2014da529eb9d"},"downloads":-1,"filename":"fastapi_exception-1.0.0.tar.gz","has_sig":false,"md5_digest":"aa3ae99d7643cfd30fa06f7fc63af088","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":11355,"upload_time":"2023-09-28T20:04:04","upload_time_iso_8601":"2023-09-28T20:04:04.969609Z","url":"https://files.pythonhosted.org/packages/de/49/955e4c6c91477978f9d4eb88f88dece5cff3509a3302440dafb90eae7df0/fastapi_exception-1.0.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.1":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.0.1/","requires_dist":["pydantic==2.4.2"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.0.1","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"a043786d4f20aefbddfa8eb95a7ba16f6366c583edec91ee2ee2406d923d117c","md5":"2d442bb5189bab3217da4d9ba596e9df","sha256":"cf458fd2b918056fa5be0f6b1d4ed89a1d971b6efd5fe1d3897407beb7433a15"},"downloads":-1,"filename":"fastapi_exception-1.0.1-py3-none-any.whl","has_sig":false,"md5_digest":"2d442bb5189bab3217da4d9ba596e9df","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":11348,"upload_time":"2023-09-28T20:18:01","upload_time_iso_8601":"2023-09-28T20:18:01.788220Z","url":"https://files.pythonhosted.org/packages/a0/43/786d4f20aefbddfa8eb95a7ba16f6366c583edec91ee2ee2406d923d117c/fastapi_exception-1.0.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"74b7290d03372823b58e4f68d323e3486d18bacfea8528bc128cf0bbb3947b3b","md5":"e18d7bb0dda4902ff28b949f4f8402fe","sha256":"8040fd801182521d5c55ca5025b3c418776237ebd96a8308005460d8f59c30a6"},"downloads":-1,"filename":"fastapi_exception-1.0.1.tar.gz","has_sig":false,"md5_digest":"e18d7bb0dda4902ff28b949f4f8402fe","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9401,"upload_time":"2023-09-28T20:18:04","upload_time_iso_8601":"2023-09-28T20:18:04.335801Z","url":"https://files.pythonhosted.org/packages/74/b7/290d03372823b58e4f68d323e3486d18bacfea8528bc128cf0bbb3947b3b/fastapi_exception-1.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.2":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.0.2/","requires_dist":["pydantic==2.4.2"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.0.2","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"7824be85444064f06d7ec1a7c218980fe408507e73b6604cf4cdbd63f92764ab","md5":"55338bf42bc5d2cc1c10f6caf2a1b630","sha256":"90f7aa09a7c197744156c5c62f3f95f475492327f1885420d9ce66ca33542bb0"},"downloads":-1,"filename":"fastapi_exception-1.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"55338bf42bc5d2cc1c10f6caf2a1b630","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":11345,"upload_time":"2023-09-28T20:26:54","upload_time_iso_8601":"2023-09-28T20:26:54.776915Z","url":"https://files.pythonhosted.org/packages/78/24/be85444064f06d7ec1a7c218980fe408507e73b6604cf4cdbd63f92764ab/fastapi_exception-1.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"953dc77c25ad7f1117064d56f13b0a0be55876871396d1ae297c47d8768de20e","md5":"60d60750c8bcfc4c9cfdae6bb419def3","sha256":"36c3852bd0a067893d2c66c4a19d953d7a092efcf2b4da5143c7438571ff10ac"},"downloads":-1,"filename":"fastapi_exception-1.0.2.tar.gz","has_sig":false,"md5_digest":"60d60750c8bcfc4c9cfdae6bb419def3","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9400,"upload_time":"2023-09-28T20:26:56","upload_time_iso_8601":"2023-09-28T20:26:56.327246Z","url":"https://files.pythonhosted.org/packages/95/3d/c77c25ad7f1117064d56f13b0a0be55876871396d1ae297c47d8768de20e/fastapi_exception-1.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.0":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.1.0/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.1.0","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"33c3ba29ce5cd4484dae6afe3d72834fdf9cc53ec46f7eac5122ffd1bcc0e117","md5":"6087bcecebba6121468248b5f68d9549","sha256":"6523119a46e67bed89820fc4f2ff0ab3df6e846cb12121bcacb659118ad2b383"},"downloads":-1,"filename":"fastapi_exception-1.1.0-py3-none-any.whl","has_sig":false,"md5_digest":"6087bcecebba6121468248b5f68d9549","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12367,"upload_time":"2023-09-29T03:34:55","upload_time_iso_8601":"2023-09-29T03:34:55.783504Z","url":"https://files.pythonhosted.org/packages/33/c3/ba29ce5cd4484dae6afe3d72834fdf9cc53ec46f7eac5122ffd1bcc0e117/fastapi_exception-1.1.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"564789638ddaa636e04c1c8a7c48539c7fe44424c706b527ee75aa905aa82a8c","md5":"4d12fcbf9eae3f7fcdad407af551b3d4","sha256":"e7c084437ed3ba0befe6357597811afacbc604d75e6fe9cf8bb5959612d389a6"},"downloads":-1,"filename":"fastapi_exception-1.1.0.tar.gz","has_sig":false,"md5_digest":"4d12fcbf9eae3f7fcdad407af551b3d4","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9621,"upload_time":"2023-09-29T03:34:57","upload_time_iso_8601":"2023-09-29T03:34:57.668528Z","url":"https://files.pythonhosted.org/packages/56/47/89638ddaa636e04c1c8a7c48539c7fe44424c706b527ee75aa905aa82a8c/fastapi_exception-1.1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.1.1":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.1.1/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.1.1","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"ae6ad7ab258ee3c03e292b370d4d20e2c941d56f5039756dadfbdf86afea06db","md5":"082209cae1725266343b6f8c9657713b","sha256":"c450534e65dc2b8123ebe593ca17429dd1a89b1f701f4bf45f2b23c696803137"},"downloads":-1,"filename":"fastapi_exception-1.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"082209cae1725266343b6f8c9657713b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12366,"upload_time":"2023-09-29T03:37:09","upload_time_iso_8601":"2023-09-29T03:37:09.564942Z","url":"https://files.pythonhosted.org/packages/ae/6a/d7ab258ee3c03e292b370d4d20e2c941d56f5039756dadfbdf86afea06db/fastapi_exception-1.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"11c1d8d52484316b0b9db1d319813191d12104c5ff9b2fbc6356558f50b8d2e7","md5":"b9f87476467e0514ad5ab192155ebab9","sha256":"3ca6a915d604df5c538efaf17ff65308b6aecb4f6435130a65dcb65851ed1b6d"},"downloads":-1,"filename":"fastapi_exception-1.1.1.tar.gz","has_sig":false,"md5_digest":"b9f87476467e0514ad5ab192155ebab9","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9620,"upload_time":"2023-09-29T03:37:11","upload_time_iso_8601":"2023-09-29T03:37:11.542799Z","url":"https://files.pythonhosted.org/packages/11/c1/d8d52484316b0b9db1d319813191d12104c5ff9b2fbc6356558f50b8d2e7/fastapi_exception-1.1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2.1":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.2.1/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.2.1","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"04aa6a2dfdde788805bd778b2e091e383c0740c96d187142a927cc1bef47861a","md5":"531752c3a39f400974012b151217b2ac","sha256":"b54a42fa1100c02ce8e4e71d78813f99dc83fe5ffdc5197dc936daea6b330671"},"downloads":-1,"filename":"fastapi_exception-1.2.1-py3-none-any.whl","has_sig":false,"md5_digest":"531752c3a39f400974012b151217b2ac","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12851,"upload_time":"2023-09-29T08:55:54","upload_time_iso_8601":"2023-09-29T08:55:54.756426Z","url":"https://files.pythonhosted.org/packages/04/aa/6a2dfdde788805bd778b2e091e383c0740c96d187142a927cc1bef47861a/fastapi_exception-1.2.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"93d6fcb805fde9c63a755f976d268fba4f69a89cc7efb58542b07f735a5f409a","md5":"c4e59c726e02ae27988e5c5ea4778231","sha256":"fd09a9132b54ddc27b65581d0fe1a29286fbbeb2d4c03bdde2329d37cd2f8ce5"},"downloads":-1,"filename":"fastapi_exception-1.2.1.tar.gz","has_sig":false,"md5_digest":"c4e59c726e02ae27988e5c5ea4778231","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9655,"upload_time":"2023-09-29T08:55:56","upload_time_iso_8601":"2023-09-29T08:55:56.786831Z","url":"https://files.pythonhosted.org/packages/93/d6/fcb805fde9c63a755f976d268fba4f69a89cc7efb58542b07f735a5f409a/fastapi_exception-1.2.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2.2":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.2.2/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.2.2","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"3f957c8148963469a5f3cf0bbdc7e4e95768fe13d6e87f80669058f30f0b3d91","md5":"a30bc3e284d872d2c22fcd374b381440","sha256":"6d949fd668eb8464e39c8326d7fa0c0f55a386341c7fa7938f2d4edbd8bda4f7"},"downloads":-1,"filename":"fastapi_exception-1.2.2-py3-none-any.whl","has_sig":false,"md5_digest":"a30bc3e284d872d2c22fcd374b381440","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12868,"upload_time":"2023-09-29T08:59:30","upload_time_iso_8601":"2023-09-29T08:59:30.596460Z","url":"https://files.pythonhosted.org/packages/3f/95/7c8148963469a5f3cf0bbdc7e4e95768fe13d6e87f80669058f30f0b3d91/fastapi_exception-1.2.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"05902f3578dcf088dd70fa3bbd08212d83763f9afabca4b2d64f42cfabc7fb17","md5":"018e7613a07d959fcdd9c564940b6804","sha256":"5a870c6a20997bee44cae9389cf7f544db4f9f0d033dbb602e3d727abd98044c"},"downloads":-1,"filename":"fastapi_exception-1.2.2.tar.gz","has_sig":false,"md5_digest":"018e7613a07d959fcdd9c564940b6804","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9668,"upload_time":"2023-09-29T08:59:32","upload_time_iso_8601":"2023-09-29T08:59:32.617802Z","url":"https://files.pythonhosted.org/packages/05/90/2f3578dcf088dd70fa3bbd08212d83763f9afabca4b2d64f42cfabc7fb17/fastapi_exception-1.2.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2.3":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.2.3/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.2.3","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"2f8c7a14905dac49f5d0262a5856f40e655d48af7ef7defe8ce3781e23d68dc1","md5":"fd07a750c42325c7dc89200bc475a2a3","sha256":"82fb07d3d1c196d5d0bb09bf79053c7484401d00f3375360bdf6284d23198712"},"downloads":-1,"filename":"fastapi_exception-1.2.3-py3-none-any.whl","has_sig":false,"md5_digest":"fd07a750c42325c7dc89200bc475a2a3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12869,"upload_time":"2023-09-29T09:03:11","upload_time_iso_8601":"2023-09-29T09:03:11.520573Z","url":"https://files.pythonhosted.org/packages/2f/8c/7a14905dac49f5d0262a5856f40e655d48af7ef7defe8ce3781e23d68dc1/fastapi_exception-1.2.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"6a05cc90a7e5afd5e135b4208386d0698eff9bc4be6179321eb0ba3d8c3bf536","md5":"c2f88547226545117caf33bb4b6a3325","sha256":"734d3547b672fbc15705dc2e2f1b003240c699025a244e1645c3014c37a9ac66"},"downloads":-1,"filename":"fastapi_exception-1.2.3.tar.gz","has_sig":false,"md5_digest":"c2f88547226545117caf33bb4b6a3325","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9671,"upload_time":"2023-09-29T09:03:13","upload_time_iso_8601":"2023-09-29T09:03:13.393537Z","url":"https://files.pythonhosted.org/packages/6a/05/cc90a7e5afd5e135b4208386d0698eff9bc4be6179321eb0ba3d8c3bf536/fastapi_exception-1.2.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2.4":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.2.4/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.2.4","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"4c8442c0b54ec0ad776f1b04ca4523b0e17875631dacb16d16a17fea66409d59","md5":"9e7167ad2fb0c29abba313dd3e292655","sha256":"c93fe19ad12b21326857da156945b38353c04803209cb499eb3c0068f610d25d"},"downloads":-1,"filename":"fastapi_exception-1.2.4-py3-none-any.whl","has_sig":false,"md5_digest":"9e7167ad2fb0c29abba313dd3e292655","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":12900,"upload_time":"2023-10-01T05:07:12","upload_time_iso_8601":"2023-10-01T05:07:12.615609Z","url":"https://files.pythonhosted.org/packages/4c/84/42c0b54ec0ad776f1b04ca4523b0e17875631dacb16d16a17fea66409d59/fastapi_exception-1.2.4-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"42700960ad68522dcec7bb4d52f0046d3d81e720f37c004c6874d1bbab3d4abf","md5":"356be2ac8f8079a820471e985090ba76","sha256":"f53b38b49a41f2d223fc5d7ae025a41bfe0081cc6603c17b054b7ff575c0d6b8"},"downloads":-1,"filename":"fastapi_exception-1.2.4.tar.gz","has_sig":false,"md5_digest":"356be2ac8f8079a820471e985090ba76","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9675,"upload_time":"2023-10-01T05:07:14","upload_time_iso_8601":"2023-10-01T05:07:14.842402Z","url":"https://files.pythonhosted.org/packages/42/70/0960ad68522dcec7bb4d52f0046d3d81e720f37c004c6874d1bbab3d4abf/fastapi_exception-1.2.4.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2.5":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.2.5/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.2.5","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"19ba80f861a7fccd39d4f89ea052180106a9731d0e04bfd883884a0613e6f927","md5":"f3f77469957788863cfa8f48f756d702","sha256":"3f84c2b691ae234bb6bdb260f813e754202f8223d05b05bc2cef7efa68449f2f"},"downloads":-1,"filename":"fastapi_exception-1.2.5-py3-none-any.whl","has_sig":false,"md5_digest":"f3f77469957788863cfa8f48f756d702","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13108,"upload_time":"2023-10-01T05:20:26","upload_time_iso_8601":"2023-10-01T05:20:26.766431Z","url":"https://files.pythonhosted.org/packages/19/ba/80f861a7fccd39d4f89ea052180106a9731d0e04bfd883884a0613e6f927/fastapi_exception-1.2.5-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"b45d7b4df6c7c90d5d19dc9a9a09237adc829a076f435ed6e512114d1f189979","md5":"b169aa19138bfa955837a83c51f77f57","sha256":"5a2a1060fa76e9164eaba09fe20e6462054da9144d7a696ed2a3f06313b1c8f2"},"downloads":-1,"filename":"fastapi_exception-1.2.5.tar.gz","has_sig":false,"md5_digest":"b169aa19138bfa955837a83c51f77f57","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9923,"upload_time":"2023-10-01T05:20:29","upload_time_iso_8601":"2023-10-01T05:20:29.157950Z","url":"https://files.pythonhosted.org/packages/b4/5d/7b4df6c7c90d5d19dc9a9a09237adc829a076f435ed6e512114d1f189979/fastapi_exception-1.2.5.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.0":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.0/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.0","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"97ea6fd44a996413ac270c8fa8c1af063f36db5999469c6600398a566435fd0d","md5":"862fb82177d80bfc62f294a4ee854545","sha256":"655b354ad80c35a7a95461ff3829a692fcadcd45b4e6ebe427473ab872c039d7"},"downloads":-1,"filename":"fastapi_exception-1.3.0-py3-none-any.whl","has_sig":false,"md5_digest":"862fb82177d80bfc62f294a4ee854545","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13018,"upload_time":"2023-10-03T04:56:15","upload_time_iso_8601":"2023-10-03T04:56:15.479508Z","url":"https://files.pythonhosted.org/packages/97/ea/6fd44a996413ac270c8fa8c1af063f36db5999469c6600398a566435fd0d/fastapi_exception-1.3.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"544d66f43a870462432a1d63252d7d3af66503bbc683a6bd812b23d46a5ffe58","md5":"9db4435cb4299e9f4f805298b0e44c50","sha256":"4e222f786dbea180a0c06df70b81afcc78cf3a82e6369a8a28a1fd26e8535a29"},"downloads":-1,"filename":"fastapi_exception-1.3.0.tar.gz","has_sig":false,"md5_digest":"9db4435cb4299e9f4f805298b0e44c50","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9804,"upload_time":"2023-10-03T04:56:17","upload_time_iso_8601":"2023-10-03T04:56:17.429365Z","url":"https://files.pythonhosted.org/packages/54/4d/66f43a870462432a1d63252d7d3af66503bbc683a6bd812b23d46a5ffe58/fastapi_exception-1.3.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.1":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.1/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.1","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"6a003b35532cd374fb3687112115ef159f4b19bf6a84b39faaa2e47d0faf5802","md5":"3a5447212edcf2b432733538c93c69da","sha256":"8ca26b6cb54e93f4dca60db1c9d9a1634c9502beacc2938bfa7e25afeefc2463"},"downloads":-1,"filename":"fastapi_exception-1.3.1-py3-none-any.whl","has_sig":false,"md5_digest":"3a5447212edcf2b432733538c93c69da","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13191,"upload_time":"2023-10-03T07:15:57","upload_time_iso_8601":"2023-10-03T07:15:57.552370Z","url":"https://files.pythonhosted.org/packages/6a/00/3b35532cd374fb3687112115ef159f4b19bf6a84b39faaa2e47d0faf5802/fastapi_exception-1.3.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"b4e551c8b8fb30053415ce0498a77dc4bf6dfbf246e94cc63112bd8f4e9b1fe4","md5":"623f3b891af62bec5ba117c5ce9051fb","sha256":"d4c049a91ade8f22127a67707d413af11110dcaec24a7c932d8ba81012f2c767"},"downloads":-1,"filename":"fastapi_exception-1.3.1.tar.gz","has_sig":false,"md5_digest":"623f3b891af62bec5ba117c5ce9051fb","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":9898,"upload_time":"2023-10-03T07:15:59","upload_time_iso_8601":"2023-10-03T07:15:59.236335Z","url":"https://files.pythonhosted.org/packages/b4/e5/51c8b8fb30053415ce0498a77dc4bf6dfbf246e94cc63112bd8f4e9b1fe4/fastapi_exception-1.3.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.10":{"info":{"author":null,"author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.10/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.6.0","python-keycloak>=2.14.0"],"requires_python":">=3.11","summary":"FastAPI Exception","version":"1.3.10","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"e153158f83e20f8ea1e434eb90e0ec90cc061ce04c24d16cb60600777533b953","md5":"834267f28dc8822ccfbedcb7eeddac22","sha256":"a66705cb84e2bb38a64f4b05229a02caa8368855bd84398db4ce6496e96d4895"},"downloads":-1,"filename":"fastapi_exception-1.3.10-py3-none-any.whl","has_sig":false,"md5_digest":"834267f28dc8822ccfbedcb7eeddac22","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.11","size":13951,"upload_time":"2024-09-10T02:55:40","upload_time_iso_8601":"2024-09-10T02:55:40.316739Z","url":"https://files.pythonhosted.org/packages/e1/53/158f83e20f8ea1e434eb90e0ec90cc061ce04c24d16cb60600777533b953/fastapi_exception-1.3.10-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"605be0b72e308321ce4b763b4a0ea258cc010ebd96ea6d1c78c551c7c9930094","md5":"a098318c7d4bc4b413d5c0f1f3446160","sha256":"f7849ab9853d3c46c1cb48eda1ff63574eabaa59ff220ff6f8a80cf23d101eee"},"downloads":-1,"filename":"fastapi_exception-1.3.10.tar.gz","has_sig":false,"md5_digest":"a098318c7d4bc4b413d5c0f1f3446160","packagetype":"sdist","python_version":"source","requires_python":">=3.11","size":11253,"upload_time":"2024-09-10T02:55:41","upload_time_iso_8601":"2024-09-10T02:55:41.664774Z","url":"https://files.pythonhosted.org/packages/60/5b/e0b72e308321ce4b763b4a0ea258cc010ebd96ea6d1c78c551c7c9930094/fastapi_exception-1.3.10.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.2":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.2/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.2","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"8bccaf853e403ebfe49afe9364c2c89af2561b28da727b87f48b416a94b0d412","md5":"6454f69580956e84427b1d63f01a79e4","sha256":"7f5f7af13dd857dc056e39e41243cec7553ac8caa0a0b5fdbafa0a18812cbb91"},"downloads":-1,"filename":"fastapi_exception-1.3.2-py3-none-any.whl","has_sig":false,"md5_digest":"6454f69580956e84427b1d63f01a79e4","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13280,"upload_time":"2023-10-03T13:40:36","upload_time_iso_8601":"2023-10-03T13:40:36.586918Z","url":"https://files.pythonhosted.org/packages/8b/cc/af853e403ebfe49afe9364c2c89af2561b28da727b87f48b416a94b0d412/fastapi_exception-1.3.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"5aa4600193ec8baa5c5c7870ddb89c20575144554465a89eae700d0f458a8da8","md5":"1e1023561be60ee1ac8c2741042370bd","sha256":"41594de4b201f032f407443885d08304d2bbb01d0670044d363de9beb51fe003"},"downloads":-1,"filename":"fastapi_exception-1.3.2.tar.gz","has_sig":false,"md5_digest":"1e1023561be60ee1ac8c2741042370bd","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":10255,"upload_time":"2023-10-03T13:40:38","upload_time_iso_8601":"2023-10-03T13:40:38.339636Z","url":"https://files.pythonhosted.org/packages/5a/a4/600193ec8baa5c5c7870ddb89c20575144554465a89eae700d0f458a8da8/fastapi_exception-1.3.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.3":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.3/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.3","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"fc477c8a085b2cfc08a7a5959409d7e894b877202c4a7cb28ce10284469db98d","md5":"3e275a5a3c7b53758fab7fd429ca96c9","sha256":"d298d37a041a33d7b8651f86929b0fb7f7dc2059b4d14f6172066a41ffd67732"},"downloads":-1,"filename":"fastapi_exception-1.3.3-py3-none-any.whl","has_sig":false,"md5_digest":"3e275a5a3c7b53758fab7fd429ca96c9","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13326,"upload_time":"2023-10-24T14:25:06","upload_time_iso_8601":"2023-10-24T14:25:06.185588Z","url":"https://files.pythonhosted.org/packages/fc/47/7c8a085b2cfc08a7a5959409d7e894b877202c4a7cb28ce10284469db98d/fastapi_exception-1.3.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"45de66e53513dbefead695c54c3f4905403b89d9ebe6c55ff29db8831330bc9f","md5":"dc078ae871942d5f6296e3c812e959e7","sha256":"6f8bc8f25d4caa493de172eec67b87dc739ded18609333a38446d2dfc13ecc42"},"downloads":-1,"filename":"fastapi_exception-1.3.3.tar.gz","has_sig":false,"md5_digest":"dc078ae871942d5f6296e3c812e959e7","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":10285,"upload_time":"2023-10-24T14:25:07","upload_time_iso_8601":"2023-10-24T14:25:07.965452Z","url":"https://files.pythonhosted.org/packages/45/de/66e53513dbefead695c54c3f4905403b89d9ebe6c55ff29db8831330bc9f/fastapi_exception-1.3.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.4":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.4/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.4","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"0cda65688da6a475b099840517efb8ee26fb1984ace1d81e5aad922c23dd3dc1","md5":"17a983503255d71a44f720b2d9f2eff7","sha256":"1a1f732d867b1ee68e5a3462707d979cbf7194bd1c96b2f10f893a251e09ba88"},"downloads":-1,"filename":"fastapi_exception-1.3.4-py3-none-any.whl","has_sig":false,"md5_digest":"17a983503255d71a44f720b2d9f2eff7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13616,"upload_time":"2024-02-27T01:40:35","upload_time_iso_8601":"2024-02-27T01:40:35.294472Z","url":"https://files.pythonhosted.org/packages/0c/da/65688da6a475b099840517efb8ee26fb1984ace1d81e5aad922c23dd3dc1/fastapi_exception-1.3.4-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"913d872bebd1066a5fdc1684d79f5fff84154c843ae17e9d81fff7d07f1a5cf0","md5":"2c550916552bce848b197384ecb611c5","sha256":"cd2efa3ca2f3d26eee817b0dbefc144378b6d2c3cbdb954eddf5b6fe835995ed"},"downloads":-1,"filename":"fastapi_exception-1.3.4.tar.gz","has_sig":false,"md5_digest":"2c550916552bce848b197384ecb611c5","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":10350,"upload_time":"2024-02-27T01:40:37","upload_time_iso_8601":"2024-02-27T01:40:37.882628Z","url":"https://files.pythonhosted.org/packages/91/3d/872bebd1066a5fdc1684d79f5fff84154c843ae17e9d81fff7d07f1a5cf0/fastapi_exception-1.3.4.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.5":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.5/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.4.2","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.5","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"631a6a4af07372327b41cbde17103ca2fef9b95b78862c23d086b7dd3f826844","md5":"ed1935ae2cee8ddc204a8da217110663","sha256":"d5cc54758f71c482396f7fab899b1c2050124bee7259646ea3c22b476608f3ea"},"downloads":-1,"filename":"fastapi_exception-1.3.5-py3-none-any.whl","has_sig":false,"md5_digest":"ed1935ae2cee8ddc204a8da217110663","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13619,"upload_time":"2024-02-27T01:42:42","upload_time_iso_8601":"2024-02-27T01:42:42.245407Z","url":"https://files.pythonhosted.org/packages/63/1a/6a4af07372327b41cbde17103ca2fef9b95b78862c23d086b7dd3f826844/fastapi_exception-1.3.5-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"54df23c23dd37382a2776f4f13082d528dffb9883ea3ba87c00aafd55d49f2a2","md5":"6e65127563cd3a0c7ea2cff8c617c9f5","sha256":"6af30044182bcc54a09120831db8e5c31c003908ebcda2021bde99526ecf9cc6"},"downloads":-1,"filename":"fastapi_exception-1.3.5.tar.gz","has_sig":false,"md5_digest":"6e65127563cd3a0c7ea2cff8c617c9f5","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":10349,"upload_time":"2024-02-27T01:42:44","upload_time_iso_8601":"2024-02-27T01:42:44.068461Z","url":"https://files.pythonhosted.org/packages/54/df/23c23dd37382a2776f4f13082d528dffb9883ea3ba87c00aafd55d49f2a2/fastapi_exception-1.3.5.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.6":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.6/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.6.0","python-keycloak>=2.14.0"],"requires_python":">=3.10","summary":"FastAPI Event","version":"1.3.6","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"6d78ee131f4965344502a170b1c35ea9350182b7676f578981e43ec16cec966e","md5":"0777a685f18e967f216a46e67926f57f","sha256":"76e2b5e6c90c87a20eb2c7a54cee504621f91f88da76e32189a5646fac7c567a"},"downloads":-1,"filename":"fastapi_exception-1.3.6-py3-none-any.whl","has_sig":false,"md5_digest":"0777a685f18e967f216a46e67926f57f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.10","size":13618,"upload_time":"2024-02-27T02:21:09","upload_time_iso_8601":"2024-02-27T02:21:09.580832Z","url":"https://files.pythonhosted.org/packages/6d/78/ee131f4965344502a170b1c35ea9350182b7676f578981e43ec16cec966e/fastapi_exception-1.3.6-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"94ce8ce35c8ce4d53227ed9eafc1f645641cef0b7119aed44f09cc0d50a3f3d8","md5":"c3b34cce876416c1432e9033a892e2cb","sha256":"8c86e0224afec4e0c67ebf10d6cae8cbc0ba3e75b1885117bca0e3f8d9ccc47c"},"downloads":-1,"filename":"fastapi_exception-1.3.6.tar.gz","has_sig":false,"md5_digest":"c3b34cce876416c1432e9033a892e2cb","packagetype":"sdist","python_version":"source","requires_python":">=3.10","size":10348,"upload_time":"2024-02-27T02:21:11","upload_time_iso_8601":"2024-02-27T02:21:11.537222Z","url":"https://files.pythonhosted.org/packages/94/ce/8ce35c8ce4d53227ed9eafc1f645641cef0b7119aed44f09cc0d50a3f3d8/fastapi_exception-1.3.6.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.7":{"info":{"author":"","author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.7/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.6.0","python-keycloak>=2.14.0"],"requires_python":">=3.11","summary":"FastAPI Event","version":"1.3.7","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"9748606b296c00c02d3dc1125230b2c6b73a4729a6f974cb4e684a1c4bce3435","md5":"44e2c8108ed1593438f8af9416025a38","sha256":"dcf0c5a1e44a661cc0ab546643ec07dfc52f133b3ba637b06c99d08e1f3b75b8"},"downloads":-1,"filename":"fastapi_exception-1.3.7-py3-none-any.whl","has_sig":false,"md5_digest":"44e2c8108ed1593438f8af9416025a38","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.11","size":13589,"upload_time":"2024-03-14T07:33:29","upload_time_iso_8601":"2024-03-14T07:33:29.075630Z","url":"https://files.pythonhosted.org/packages/97/48/606b296c00c02d3dc1125230b2c6b73a4729a6f974cb4e684a1c4bce3435/fastapi_exception-1.3.7-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"aaa758f09423725ca3143662fd3669a9d91d99c6acf30b10d345aa1a28824b51","md5":"48c81fea19dfbd436e71f8edbd0d9ae6","sha256":"07ab4dc31cb2807df8011bb4933c146e5448f9f2e4591c14a00ba0df47cf24f2"},"downloads":-1,"filename":"fastapi_exception-1.3.7.tar.gz","has_sig":false,"md5_digest":"48c81fea19dfbd436e71f8edbd0d9ae6","packagetype":"sdist","python_version":"source","requires_python":">=3.11","size":10847,"upload_time":"2024-03-14T07:33:30","upload_time_iso_8601":"2024-03-14T07:33:30.809277Z","url":"https://files.pythonhosted.org/packages/aa/a7/58f09423725ca3143662fd3669a9d91d99c6acf30b10d345aa1a28824b51/fastapi_exception-1.3.7.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.8":{"info":{"author":null,"author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.8/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.6.0","python-keycloak>=2.14.0"],"requires_python":">=3.11","summary":"FastAPI Event","version":"1.3.8","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"5ecbb1b0bfa6f298f7369d9e792bc993d0d626b1c0179fb26b5cbd4f91c4e2bc","md5":"8631b0f23fe44da07977c974db1abba3","sha256":"f1e684b3c5e1958ebd058c6c6ec759fb14ec00ee66d44dfafc9746a2835e355f"},"downloads":-1,"filename":"fastapi_exception-1.3.8-py3-none-any.whl","has_sig":false,"md5_digest":"8631b0f23fe44da07977c974db1abba3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.11","size":13602,"upload_time":"2024-03-29T04:31:53","upload_time_iso_8601":"2024-03-29T04:31:53.178145Z","url":"https://files.pythonhosted.org/packages/5e/cb/b1b0bfa6f298f7369d9e792bc993d0d626b1c0179fb26b5cbd4f91c4e2bc/fastapi_exception-1.3.8-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"124dca40f40f0698a2884e1abd8250ad569a6befa6a3748c9f38822dbf970e24","md5":"b7e3bba54189b503762773ad58d5e426","sha256":"ab2125783cf1b08616d7fe488580352f345a319ffe063d17eceed91f98d1ffae"},"downloads":-1,"filename":"fastapi_exception-1.3.8.tar.gz","has_sig":false,"md5_digest":"b7e3bba54189b503762773ad58d5e426","packagetype":"sdist","python_version":"source","requires_python":">=3.11","size":10862,"upload_time":"2024-03-29T04:31:55","upload_time_iso_8601":"2024-03-29T04:31:55.238568Z","url":"https://files.pythonhosted.org/packages/12/4d/ca40f40f0698a2884e1abd8250ad569a6befa6a3748c9f38822dbf970e24/fastapi_exception-1.3.8.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.3.9":{"info":{"author":null,"author_email":"Dzung Nguyen <dung@megatron-solutions.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"fastapi-exception","package_url":"https://pypi.org/project/fastapi-exception/","platform":null,"project_url":"https://pypi.org/project/fastapi-exception/","project_urls":{"Bug Tracker":"https://github.com/megatron-global/fastapi-exception/issues","Homepage":"https://github.com/megatron-global/fastapi-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/fastapi-exception/1.3.9/","requires_dist":["fastapi-global-variable>=0.0.4","pydantic>=2.6.0","python-keycloak>=2.14.0"],"requires_python":">=3.11","summary":"FastAPI Event","version":"1.3.9","yanked":false,"yanked_reason":null},"last_serial":24954320,"urls":[{"comment_text":"","digests":{"blake2b_256":"7f3562109879f199659a31d5a734859ed6bddda0c1accd1ed4ce565f7e2e3e96","md5":"f29d3d62ce6d7276e93a82bb68870b86","sha256":"829341018c9c50f9fa7ffbd01cc8dd76b792edeec51fbccafc0f3140ee2f60ca"},"downloads":-1,"filename":"fastapi_exception-1.3.9-py3-none-any.whl","has_sig":false,"md5_digest":"f29d3d62ce6d7276e93a82bb68870b86","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.11","size":13950,"upload_time":"2024-09-09T14:55:24","upload_time_iso_8601":"2024-09-09T14:55:24.547587Z","url":"https://files.pythonhosted.org/packages/7f/35/62109879f199659a31d5a734859ed6bddda0c1accd1ed4ce565f7e2e3e96/fastapi_exception-1.3.9-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"87f8903719b7d88a3b28058f9c8d6281404c0b8b51fe963e454f3a7537fd3019","md5":"d9f999e4ccd7be86f40f42be861f6592","sha256":"1a8a1cd7d02f0ec82f0228fac320f39eb4cdcd46b4341f86c9a58c787e60fe86"},"downloads":-1,"filename":"fastapi_exception-1.3.9.tar.gz","has_sig":false,"md5_digest":"d9f999e4ccd7be86f40f42be861f6592","packagetype":"sdist","python_version":"source","requires_python":">=3.11","size":11255,"upload_time":"2024-09-09T14:55:25","upload_time_iso_8601":"2024-09-09T14:55:25.842837Z","url":"https://files.pythonhosted.org/packages/87/f8/903719b7d88a3b28058f9c8d6281404c0b8b51fe963e454f3a7537fd3019/fastapi_exception-1.3.9.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}