{"0.3.3":{"info":{"author":"cyan","author_email":"","bugtrack_url":null,"classifiers":[],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"exception.py","package_url":"https://pypi.org/project/exception.py/","platform":null,"project_url":"https://pypi.org/project/exception.py/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/exception.py/0.3.3/","requires_dist":null,"requires_python":"","summary":"Except.Py that Make *unexceptional* problem","version":"0.3.3","yanked":false,"yanked_reason":null},"last_serial":18425261,"urls":[{"comment_text":"","digests":{"blake2b_256":"8fd35cbc71af77af9afc05bd9b6dd39d3f9cd76dcc8835894ab14342fb811e79","md5":"2afc1834c0425712870e01ee654c2ef6","sha256":"f94a5502c4617e6c4ce84aa8571450f8b20b6a0a297f882f3127be2c6bc3724a"},"downloads":-1,"filename":"exception.py-0.3.3-py3-none-any.whl","has_sig":false,"md5_digest":"2afc1834c0425712870e01ee654c2ef6","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":7639,"upload_time":"2023-05-02T06:15:10","upload_time_iso_8601":"2023-05-02T06:15:10.123771Z","url":"https://files.pythonhosted.org/packages/8f/d3/5cbc71af77af9afc05bd9b6dd39d3f9cd76dcc8835894ab14342fb811e79/exception.py-0.3.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"98e894889166c9f1327f6b7249b245f172acb13d2caeebc0bf67fbab708b5beb","md5":"48f18a996571294e7f4cdd8c2bf5487f","sha256":"ca39730c6e17138f1715f001ddccfc59307c10f0fdc55883b0c004b6b26d5160"},"downloads":-1,"filename":"exception.py-0.3.3.tar.gz","has_sig":false,"md5_digest":"48f18a996571294e7f4cdd8c2bf5487f","packagetype":"sdist","python_version":"source","requires_python":null,"size":2800,"upload_time":"2023-05-02T06:15:12","upload_time_iso_8601":"2023-05-02T06:15:12.781444Z","url":"https://files.pythonhosted.org/packages/98/e8/94889166c9f1327f6b7249b245f172acb13d2caeebc0bf67fbab708b5beb/exception.py-0.3.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.4":{"info":{"author":"cyan","author_email":"","bugtrack_url":null,"classifiers":[],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"exception.py","package_url":"https://pypi.org/project/exception.py/","platform":null,"project_url":"https://pypi.org/project/exception.py/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/exception.py/0.4/","requires_dist":null,"requires_python":"","summary":"Except.Py that Make *unexceptional* problem","version":"0.4","yanked":false,"yanked_reason":null},"last_serial":18425261,"urls":[{"comment_text":"","digests":{"blake2b_256":"a527465069a45f3feb4646c1428a4d3661840b66ddc9ebfe3ee68e906e3cf8ff","md5":"de719d54d7b233f42c5b30fee98fbba7","sha256":"2a8c367917381222f72ab2842926394dc46ab060983040dc054a368b6d0b29b7"},"downloads":-1,"filename":"exception.py-0.4-py3-none-any.whl","has_sig":false,"md5_digest":"de719d54d7b233f42c5b30fee98fbba7","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":7818,"upload_time":"2023-06-08T13:06:44","upload_time_iso_8601":"2023-06-08T13:06:44.717071Z","url":"https://files.pythonhosted.org/packages/a5/27/465069a45f3feb4646c1428a4d3661840b66ddc9ebfe3ee68e906e3cf8ff/exception.py-0.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}